### ISSUE TITLE
Xowa ver 3.12.1.1 fails to copy page contents to clipboard in page EDIT mode.

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#114]
I opened **Donald Trump** page, and went to page **EDIT**, and tried to copy page contents to clipboard using **CTRL INS** keyboard command, but it failed to do so. I knew this was a fault that has crept in, because I have done this in the past.

To verify this I opened my old **Xowa ver  2.6.5.1** and I was able to copy contents to clipboard using **CTRL INS**.

This function is useful for copying original page contents and saving in TXT as backup, in case one messes up the editing in Xowa.

**Comment by gnosygnu** [comment]
Hi! Thanks for the excellent write-up!

You're right, this was broken in a recent release: v3.3.4.1. It looks like CTRL+INS now overrides the copy function and does "decrease font size instead. I fixed it now in this commit: https://github.com/gnosygnu/xowa/commit/68674ace83c39f6fabd28b95d77d44bbb0593076 . Unfortunately, I can't make a build right now, because I'm making a lot of changes to the Config System.

If you want to work around it on your side, try the following:
* Go to home/wiki/Options/Shortcuts
* Look for "Decrease Font Size"
* Change "Ctrl + Minus" to "None"
* Press Save in the upper right hand tab
* Close the tab and reopen "home/wiki/Options/Shortcuts" (this is another bug: the immediate refresh shows the old value even though it was changed. You need to reload the page to get the new value)
* Make sure that "Decrease Font Size" still says "None"
* Edit any page and do "CTRL+INS". It should now copy the page

Out of curiosity, why do you prefer CTRL+INS to CTRL+C ? I use the latter all the time, but never the former.

**Comment by XowaWilliam** [comment]
Thanks for prompt response, and the temp work around.

> Out of curiosity, why do you prefer CTRL+INS to CTRL+C ? I use the latter all the time, but never the former.

It's many years of using it in Notepad++ and many other programs in which this feature works. It is so habitual that I never even thought of considering CTRL+C as an alternative, even though I was aware of it.

**Comment by gnosygnu** [comment]
Sorry, missed the last reply

>  It is so habitual that I never even thought of considering CTRL+C as an alternative, even though I was aware of it.

Good point. I forget the Windows cmd prompt also has the same copy shortcut. (I actually use the mouse for that.)

At any rate, this issue was also resolved in tonight's release: https://github.com/gnosygnu/xowa/releases . As such, I'm going to go ahead and close this ticket out. Let me know if there is anything else. Thanks!
