### ISSUE TITLE
error to export apk in eclips

### ISSUE THREAD

**Issue by mspmsp** [gnosygnu/xowa#116]
Hi,
I have  a problem for export project to create apk.

Native libraries detected in 'sqlite-jdbc-3.8.11.2.jar'. See console for more information.
The library 'sqlite-jdbc-3.8.11.2.jar' contains native libraries that will not run on the device.
 The following libraries were found:
  - org/sqlite/native/ARM/libsqlitejdbc.so
  - org/sqlite/native/FreeBSD/amd64/libsqlitejdbc.so
 - org/sqlite/native/Linux/arm/libsqlitejdbc.so
 - org/sqlite/native/Linux/armhf/libsqlitejdbc.so
 - org/sqlite/native/Linux/x86/libsqlitejdbc.so
 - org/sqlite/native/Linux/x86_64/libsqlitejdbc.so
 - org/sqlite/native/Mac/x86/libsqlitejdbc.jnilib
 - org/sqlite/native/Mac/x86_64/libsqlitejdbc.jnilib

**Comment by gnosygnu** [comment]
Hi! Thanks for the detailed error message!

I haven't tried to export the apk from Eclipse. For XOWA Android (https://github.com/gnosygnu/xowa_android), I use Android Studio and generate the APKs therein. The build.gradle doesn't include the sqlite jar, so there shouldn't be any issues.

Is there any reason you're using Eclipse over Android Studio? I personally do prefer Eclipse, but since the XOWA Android code base uses the Wikipedia Mobile app, I decided to use Android Studio for the XOWA Android app.

Let me know if there's something else.

Thanks!

**Comment by gnosygnu** [comment]
I'm marking this issue as "needs more information" and closing it for now. Feel free to reopen if you want to continue investigating. Thanks.
