### ISSUE TITLE
October 2016 commons.wikimedia.org does not display images offline.

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#126]
I downloaded all the files for **commons.wikimedia.org** manually from [https://archive.org/download/Xowa_commonswiki_latest](https://archive.org/download/Xowa_commonswiki_latest)

I then extracted all files to **E:\Xowa Wiki Commons\wiki\commons.wikimedia.org** directory, and tested the **checksums** of all files, which all passed.

Upon launching **commons.wikimedia.org** in offline mode, I could navigate to any page I wanted, however none of the many links I clicked on, revealed any images at all. 
All that could be seen is empty place holders. _( Image below )_
If I went online, only then would the images load from the internet instead.

Unless there is some unique setting to inhibit images in **commons.wikimedia.org** , it appears that there might be a bug in the **October 2016 commons.wikimedia.org**  build, in respect of the image database.

This procedure was tested in latest **xowa_app_windows_64_v3.11.2.8** as well as older **xowa_app_windows_64_v3.8.1.2** yielding same results, while other wiki's like **en.wikipedia.org** worked fine.

![xowa-commons-wiki](https://cloud.githubusercontent.com/assets/12995082/22542200/522673d2-e933-11e6-81e8-bfcc047a678c.jpg)

**Comment by gnosygnu** [comment]
Hi! Thanks for the clear write-up.

Unfortunately, this is expected behavior. The files at https://archive.org/download/Xowa_commonswiki_latest are primarily for wikitext (<code>\_text\_</code>). They contain no offline images (<code>\_file\_</code>)

Keep in mind that the **original** offline images for commons wikimedia could be as much as 22 TB. I think I did **mainspace thumbnails** only a few years ago, but that would still be a few dozen GB. Your example is for the Commons namespace (the "Commons" in your "Commons:Featured Pictures") and that could make it much more

Let me know how important having Commons is for you on your side. Keep in mind that's it hard enough for me to get people to download and share 100 GB of data. Trying to do the same for a wiki with an upper bound of 22 GB would be a different matter entirely

Thanks!

**Comment by XowaWilliam** [comment]
I just assumed that there would be thumbnail images similar to en.wikipedia.org
I would not be interested in downloading TB of data.
You can close this.

**Comment by gnosygnu** [comment]
Cool. Thanks for confirming. I'll close out the ticket.
