### ISSUE TITLE
Navigate Articles by Page_ID

### ISSUE THREAD

**Issue by shopuz** [gnosygnu/xowa#129]
The online version of wikipedia allows to view an article given its page_id through the URL `https://en.wikipedia.org/wiki/?curid=page_id` 
Example page_id for article Alabama is 303
So corresponding URL is `https://en.wikipedia.org/wiki/?curid=303`

Can we achieve this in XOWA ?
P.S I am quite new to this system so trying to get my head around it.

**Comment by gnosygnu** [comment]
Hi! Thanks for the interest in XOWA!

Yes, a query_string for curid is definitely possible. XOWA already does some limited query_string support with action=edit and redirect=no.

It should be a simple thing Let me look at it for the next release.

**Comment by shopuz** [comment]
Awesome.. Thanks @gnosygnu 👍

**Comment by gnosygnu** [comment]
I added this to the next release, which is tentatively scheduled for this weekend.

As a minor note, it's worth noting this feature allow a very minor form of phishing attack. So a url like https://en.wikipedia.org/wiki/Trust?curid=428364 actually goes to the article on Phishing instead of the article on Trust . I don't think there's anyway to exploit this, but I thought it worth mentioning, especially since I need to implement the same in XOWA

Let me know if you need this feature early, and I'll make a preview build for you. Otherwise, I'll mark this ticket closed in a few days.

Thanks!

**Comment by shopuz** [comment]
Thats great @gnosygnu 
Thank you so much for doing it real quick. I am happy to wait till next release.

Cheers :)

**Comment by gnosygnu** [comment]
This is included in tonight's v4.3 release. I tested with <code>en.wikipedia.org/wiki/?curid=303</code> as well as several others.

I'm going to mark the issue closed. If you run into any issues, feel free to reopen.

Thanks.
