### ISSUE TITLE
Personal Wikis unable to use templates

### ISSUE THREAD

**Issue by PentagularDark** [gnosygnu/xowa#132]
When attempting to use templates in personal wikis, it instead only renders an empty link to where the template should be located.  No apparent way to import needed templates

**Comment by gnosygnu** [comment]
Hi! Thanks for creating the issue.

Unfortunately, I was unable to reproduce it. Here's what I did in my personal wiki:
* Entered <code>Template:Test</code> in the url bar
    * This took me to a blank page called <code>Template:Test</code>
* Entered the following text in the main text box: <code>a test transclusion</code>
* Pressed <code>Save page</code>
* Went back to the main page of my wiki. In my case, I did<code>Main_Page</code> in the url bar
* Went into edit mode
* Entered <code>{{Test}}</code> in the text box.
* Pressed <code>Save page</code>
* I got <code>a test transclusion</code>

Does this match what you did?

**Comment by PentagularDark** [comment]
I must have been doing the process incorrectly before, as now they work perfectly. Although my method was very close to this.

**Comment by gnosygnu** [comment]
Cool. Thanks for the follow-up. Let me know if you are able to reproduce the issue from before. For what it's worth, template support should be pretty solid as it's been there since the initial XOWA release.

Also, I've added the instructions above to the Main Page help, so hopefully it will help out other users.

Thanks
