### ISSUE TITLE
Wikipedia-like API for XOWA

### ISSUE THREAD

**Issue by shopuz** [gnosygnu/xowa#133]
I know I might be asking a lot here but I was wondering if we can setup an API for XOWA much similar to Wikipedia. My current use case is to get appropriate image for an article.

In Wikipedia API, the URL `https://en.wikipedia.org/w/api.php?action=query&prop=pageimages&format=json&piprop=original&titles=Australia` would give the original as well as thumbnail URIs for the images. Is there any way we can achieve this here ?

I understand that the images are stored in the database under `*file-*.xowa` and extracted upon page load. Could you direct me to an appropriate way to extract original and thumbnail versions of the image along with its relationship with the article title ?

**Comment by gnosygnu** [comment]
Hi, thanks for the detail!

First, a little background. XOWA stores the exact images that each page uses. Note that it stores one of the following:
* The original image if the full original image is shown on the page. This is fairly rare and would require the page to use something like <code>[[File:Image_1.png]]</code>
* The thumbnail of the image as its shown on the page. This is the more common case, as most pages just use thumbs like <code>[[File:Image_1.png|300px]]</code>

For the thumbnail, XOWA stores a separate copy for different resolutions. So, if Page_1 uses Image_1.png at 300 width (<code>[[File:Image_1.png|300px]]</code>), and Page_2 uses Image_1.png at 200 width (<code>[[File:Image_1.png|200px]]</code>), there will be two thumbs in the database: a 300px one and a 200px one. Note that if no page in the wiki uses Image_1.png in its "original" form (<code>[[File:Image_1.png]]</code>), then the original would **not** be stored in the database.

With that said, XOWA can sort of substitute for the API.

First, there is a special page to get info on a specific image. For example, navigate to the following url in XOWA to get info on <code>The_Earth_seen_from_Apollo_17.jpg</code>: <code>en.wikipedia.org/wiki/Special:XowaDiag?type=file.check&wiki=en.wikipedia.org&file=The_Earth_seen_from_Apollo_17.jpg</code>

Note that this does two things:
* Lists some metadata on the row in question as well as the SELECT SQL
* Outputs every available original and thumb to <code>C:\xowa\wiki\en.wikipedia.org\tmp</code>

So, with that said and done, one could do the following today:
* Run a command-line to get the HTML of a page. For example, to get the HTML for Earth, run <code>java -jar xowa_windows_64.jar --app_mode cmd --show_license n --show_args n --cmd_text "app.shell.fetch_page('en.wikipedia.org/wiki/Earth' 'html');"</code>
* Have something that parses the HTML to get the images
* For each image, run a command-line to get the actual image. For example, to get the HTML for The_Earth_seen_from_Apollo_17.jpg, run <code>java -jar xowa_windows_64.jar --app_mode cmd --show_license n --show_args n --cmd_text "app.shell.fetch_page('en.wikipedia.org/wiki/Special:XowaDiag?type=file.check&wiki=en.wikipedia.org&file=The_Earth_seen_from_Apollo_17.jpg' 'html');"</code>
* Have something that parses this HTML to get the actual file path to the image

Obviously, this isn't as simple as a single API call, and requires some legwork.

There's also a second option. XOWA has a page_id to file_id mapping database which I don't release. I can start releasing it, and if you're ok with SQL, you can do the joins from page_id to file_id to get your data. Note that this also requires legwork on your side. You may also need some guidance from me to navigate the SQL tables, though honestly there are less than ten, and it should be sort of deducible.

Thirdly, I think it's possible to make a more streamlined API via a special page. For example, something like <code>en.wikipedia.org/wiki/Special:XowaFileDump?title=Earth&dir=C:\xowa\file_dump</code> where the title and directory is passed in.

So, my advice is:
* Take a look at the first one, and see how far that gets you. Try it with whichever images you're interested in and see if you would actually use the image that gets dumped out.
* If you're interested in the second one (and have the SQL experience to navigate the tables and Java experience to write the code), let me know and I'll upload the second database. It's about 816 MB

If you're interested in the third one, there's another bunch of questions:
* Would you want to do this as a command-line call or can you use XOWA as an HTTP server, or even directly as a library jar? I think command-line is simple, but there's a lot of performance penalty for starting and stopping the app for each request. The HTTP-server request would avoid the app-startup cost. Using XOWA directly as a Java library would be best
* Would the thumbnail be suitable for your use? In most cases, the original is not available. The thumbnail is available, but it's often lower-quality.
* How much do you think you'd actually use this feature? I'd figure this would take me several hours to code. I'd be ok with coding it, as it has some utility, but would just like some assurance that this would be a frequently-used feature -- especially in the immediate future.

Finally, just so you know, I thought I would release tonight, but it turns out I'm not releasing until Tuesday. Hope you can wait for the curid feature until then.

Let me know what you think. Thanks!

**Comment by shopuz** [comment]
I would love to go ahead with the first approach when I have some time to look into this. 

Thanks for such good explanation @gnosygnu

**Comment by gnosygnu** [comment]
I'm marking this as a future enhancement, and will mark it closed in a few days. If you're still interested in the feature, let me know, and I'll reopen the issue and try to slot some time for it.

Thanks!

**Comment by gnosygnu** [comment]
As per above, I'm marking this issue as a future enhancement, and will revisit again, should time ever permit. In the meantime, I'm going to close out this issue. Thanks.

**Comment by MatsGej** [comment]
I have a few needs around an API
* I want to use a API from my python script to get the information about a point of interests (pois)
* I would like to be able to do a nearby place search for pois using the gps coordinates

Is it possible to do this in some way with XOWA?
