### ISSUE TITLE
Question about removing outdated files in en.wikipedia.org

### ISSUE THREAD

**Issue by markusmaresch** [gnosygnu/xowa#136]
I have asked a similar question before - sorry, just wanted to make sure, and maybe in the interest of others: 
Directory: xowa/wiki/en.wikipedia.org .. after the recent 2017/02 update
There are many files occupying lots of space, which were NOT updated - can they go for a 'normal' PC/Mac Installation ?

ls -al en.wikipedia.org-html* .... 61GB   (deletable ?)
ls -al en.wikipedia.org-file-ns.* .... 109GB (should stay ?, higher numbers 61-70 are newer)

Thanks - cool program and cool project
:-)
Markus

**Comment by markusmaresch** [comment]
Correction - first item should read:
ls -al en.wikipedia.org-html-db.0* .... 33GB (can this be deleted ?)
Needed: en.wikipedia.org-html-ns.* !!

**Comment by gnosygnu** [comment]
Hi Markus. :)

> There are many files occupying lots of space, which were NOT updated - can they go for a 'normal' PC/Mac Installation ?

The short answer is probably no. None of your files are deleteable. A complete English Wikipedia is about 150 GB:
* 30 GB: HTML articles, search and core functions
* 30 GB: Category
* 90 GB: Images

Here's a longer answer:

The HTML databases are around 61 GB now.
* However, 30 GB are from Category alone. If you don't use them, you can delete them.
* Otherwise, the other 30 GB are needed.
* Note that the entire 60 GB is regenerated every month. If you download a new month's 60 GB, you can then delete the old month's 60 GB.

The File databases for 2017-02 had two options:
* New users: download the full 90 GB set
* Existing users: download a smaller 6 GB set. After downloading, the set would be around 110 GB. You would then run a separate task to compact the existing set to get back down to 90 GB.

More likely than not, you downloaded the smaller 6 GB set.
* Note that these would have new copies of databases 68-70 (not 61-70)
* The other databases (1-67) are not updated but cannot be deleted. If you do delete them, you'll lose the images

If you're interested in compressing them, check out the instructions at http://xowa.org/home/wiki/Blog.html . Or ask for more help here.

Hope this helps.

Thanks!

**Comment by gnosygnu** [comment]
Hey, I'm marking this question answered and will probably close it out in a few days. Let me know if I missed anything. Thanks!

**Comment by khanhhung2512** [comment]
> If you're interested in compressing them, check out the instructions at http://xowa.org/home/wiki/Blog.html . Or ask for more help here.

Where are the instructions? I don't see them. Btw, how long does compressing them normally take?

**Comment by gnosygnu** [comment]
I think all questions have been answered in this issue, so I'm going to close this issue. Let me know if I missed anything, and I'll reopen. Thanks.
