### ISSUE TITLE
xowa does not start

### ISSUE THREAD

**Issue by bilde2910** [gnosygnu/xowa#14]
Hi! Sorry if this is something you already know about; I tried looking through the open issues, but nothing seems to match the problem I've got. Just downloaded xowa v2.7.3.3, extracted it on an external drive (`T:`) on a Windows 8.1 x64 machine. Launching the app via cmd (`java -jar xowa_windows_64.jar`) gives me the following output:

    T:\Marius\Wikipedia>java -jar xowa_windows_64.jar
    XOWA: the XOWA Offline Wiki Application
    Copyright (c) 2012 gnosygnu@gmail.com

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    --------------------------------------------------------------------------------

    version: 2.7.3.3; build date: 2015-07-21 23:34

    arguments:
      **** NONE ****
      use --help to show help

    Exception in thread "main" org.eclipse.swt.SWTError: Unknown error
        at org.eclipse.swt.internal.mozilla.nsISupports.getMethodIndex(Unknown Source)
        at org.eclipse.swt.internal.mozilla.nsIFile.Create(Unknown Source)
        at org.eclipse.swt.browser.AppFileLocProvider.<init>(Unknown Source)
        at org.eclipse.swt.browser.Mozilla.create(Unknown Source)
        at org.eclipse.swt.browser.Browser.<init>(Unknown Source)
        at gplx.gfui.Swt_html.<init>(Unknown Source)
        at gplx.gfui.Swt_kit.New_html(Unknown Source)
        at gplx.xowa.gui.views.Xog_tab_itm.Make_html_box(Unknown Source)
        at gplx.xowa.gui.views.Xog_tab_mgr.Tabs_new(Unknown Source)
        at gplx.xowa.gui.views.Xog_tab_mgr.Tabs_new_init(Unknown Source)
        at gplx.xowa.gui.views.Xog_launcher_tabs.Launch_tab(Unknown Source)
        at gplx.xowa.gui.views.Xog_launcher_tabs.Restore_tabs(Unknown Source)
        at gplx.xowa.gui.views.Xog_launcher_tabs.Launch(Unknown Source)
        at gplx.xowa.gui.views.Xog_tab_itm_read_mgr.Launch(Unknown Source)
        at gplx.xowa.gui.Xoa_gui_mgr.Run(Unknown Source)
        at gplx.xowa.Xoa_app_boot_mgr.Run_app(Unknown Source)
        at gplx.xowa.Xoa_app_boot_mgr.Run(Unknown Source)
        at gplx.xowa.Xoa_app_.Run(Unknown Source)
        at gplx.xowa.Xowa_main.main(Unknown Source)

Java version 1.8.0_45-b14, also tried on 1.7.0_72-b14 without success. Also tried moving the files to C:\xowa without success. The exe launcher does nothing when double-clicked. Let me know if I can supply any more informaiton, and I'll be glad to.

**Comment by gnosygnu** [comment]
Hey! Thanks for the console output! It was incredibly helpful.

XOWA is failing because of SWT (the internal GUI library). I'm not sure why but the getMethodIndex may be related to version incompatibility.

Can you try installing a version from my Google Drive?: https://drive.google.com/file/d/0B9cb52zjL2rIbUFSREloanpfcDA/view?usp=sharing . This is the same package as the current Windows 64 one except for the following:

* Has SWT v4.4: bin\windows_64\swt
* Has XULRunner v24: bin\windows_64\xulrunner_v24
* Changes the boot to use xulRunner v24: bin\windows_64\xowa\cfg

These are the same steps I recommended in https://github.com/gnosygnu/xowa/issues/9 . Unfortunately, the user never got back to me about SWT v4.4 .

I'm hoping this works. If not, I'll just keep climbing down the ladder (SWT 4.3; XULRunner v17; SWT v4.2; XULRunner v10) until it does.

Thanks!

**Comment by bilde2910** [comment]
Thanks for getting back to me, I'm just glad I can be of help.

I can confirm that the version you posted launches properly on my machine. No remaining traces of errors in console output. The exe file also launches fine. I will let you know if I encounter any other errors!

**Comment by gnosygnu** [comment]
Cool! Thanks for the quick follow-up!

Can I ask one other favor? The version I gave you has SWT 4.4. I'd like to see if SWT 4.5 works. SWT 4.4 has one bug that will prevent you from editing pages.

You can try either of these two things:

* Replace your SWT at bin\windows_64\swt\swt.jar with this version from my Google drive: https://drive.google.com/file/d/0B9cb52zjL2rIQ2g0c3Bua0Vya1k/view?usp=sharing
* Or download a new version with SWT 4.5 from my Google drive: https://drive.google.com/file/d/0B9cb52zjL2rINlFpREo0bExnMW8/view?usp=sharing

The first will probably be quicker, but the second may be easier.

If you don't get a chance to do it, no biggie. I really appreciate the feedback!

Thanks again!

**Comment by bilde2910** [comment]
Hi again! I can confirm that both replacing the swt.jar in the existing xowa download and downloading xowa anew from the link you gave me work without any problems. The swt.jar from the non-functioning download also works when copied into the working environment. As a side-note, I noticed that Alt+F4 doesn't work if any tabs are open, you have to Ctrl+W away all open tabs before Alt+F4 closes xowa. This happens on all of the swt.jars. Should I create this as a separate issue?

**Comment by gnosygnu** [comment]
> I can confirm that both replacing the swt.jar in the existing xowa download and downloading xowa anew from the link you gave me work without any problems.

Great! Thanks for trying them both out! The downgrade to XULRunner24 will be part of the next release (this Monday).

By the way, I like to credit users with detecting / reporting bugs. Right now, there's a line in the XOWA change log like "Use XULRunner24 for Windows package due to Windows 8.1 {detected by anonymous}" Let me know if you'd like to be known by another nick, or would rather remain anonymous.

> As a side-note, I noticed that Alt+F4 doesn't work if any tabs are open, 

I just noticed that I can get the same thing to not work on my machine if I click on the HTML browser and press Alt+F4. If I click on the URL bar and press Alt+F4, it always work.

I'll look at why Alt+F4 doesn't work when the browser has focus. Would you confirm whether or not Alt+F4 works when the URL bar has focus (i.e.: click on URL bar -> Press Alt+F4)

Again, thanks!

**Comment by bilde2910** [comment]
Sorry for not coming back to you sooner. I replied to the e-mail I got from GitHub about your comment on this issue, but apparently it was not posted.

It doesn't really matter to me if I am credited or not. If I had to choose, though, I'd probably want to remain anonymous, more or less because I like the feeling of just contributing in order to improve the software, as opposed to contributing in order to be accredited. That's just me, though.

I can reproduce the Alt+F4 issue exactly like how you describe it. However, I see that you fixed that issue in #15. Thanks for fixing the issues so swiftly!

**Comment by gnosygnu** [comment]
> Sorry for not coming back to you sooner.

No worries. Quite glad to have the follow-up.

> It doesn't really matter to me if I am credited or not

Not a problem! "Anonymous" you'll remain. Feel free to change your mind later.

> I can reproduce the Alt+F4 issue exactly like how you describe it. However, I see that you fixed that issue in #15. Thanks for fixing the issues so swiftly!

No problem, but I could only fix the issue swiftly thanks to your swift reporting. Again, thanks for the help!

**Comment by gnosygnu** [comment]
I was able to reproduce a similar issue on a loaner Windows 8.1 (with a 32 bit JVM). I managed to fix this issue by upgrading to SWT 4.6M1 (but keeping XULRunner at v24).

If you get a chance, please try out version v2.8.2 at https://github.com/gnosygnu/xowa/releases

Thanks.

**Comment by bilde2910** [comment]
Hi! I can confirm that v2.8.2.1 works on my system.

**Comment by gnosygnu** [comment]
Great! Thanks for the confirmation!
