### ISSUE TITLE
Request for Hindi and Tibetan(if available) wikis with images

### ISSUE THREAD

**Issue by cyberorg** [gnosygnu/xowa#140]
Hi, could you please make Hindi and Tibetan wikis including images available too.

Thanks

**Comment by gnosygnu** [comment]
Hi! Good to hear from you again.

You're in luck. I was working on the Russian wikis today, and had some time to squeeze in Hindi and Tibetan. I generated the wikis and uploaded them just now. To get them, see the instructions below

Just a few notes:
* Tibetan Wiktionary and Wikibooks had only 1 and 2 articles respectively so I didn't upload them
* Hindi Wikipedia has a lot of errors on references. This is due to a bad edit for Template:Cite_web. They reverted it on March 4th, after the dump. You can fix this on your side by doing the following
    * Open your web browser and go to hi.wikipedia.org/wiki/साँचा:Cite_web?title=Template:Cite_web&action=edit
    * Copy the text
    * Open XOWA and go to hi.wikipedia.org/wiki/Template:Cite_web
    * Click Edit
    * Paste the text
    * Save the page
    * You can check this with hi.wikipedia.org/wiki/हिन्दी

Let me know if you run into any issues. Otherwise, I'll close the ticket out in a few days.

Thanks!

----

* Go to Download Central
    * On XOWA: Tools -> Download Central (also home/wiki/Special:XowaDownloadCentral)
    * ON XOWA Android: Left menu -> XOWA -> Download button
* On the "Available" table, click the "blue down arrow" all the way to the right
* You'll see a status message in the bottom right about the recent additions
* Select <code>Hindi</code> or <code>Tibetan</code>from the language dropdown
* Add the wikis and download

**Comment by cyberorg** [comment]
Hi, thanks for making these available so quickly.

How often do you update them?

Will be installing Tibetan wiki soon, here: http://www.tcv.org.in/content/tcv-suja

**Comment by gnosygnu** [comment]
> Hi, thanks for making these available so quickly.

Hey, no problem. Glad to help. :)

> How often do you update them?

For now, I'm updating wikis on demand. Only English Wikipedia is updated every month (I use it a lot), with German / French updated every other month. I'd like to update them more regularly, but I need to automate a lot of steps, which is a pretty time-intensive effort on my side.

If you want to learn how to build them on your side, let me know. I put up instructions at http://xowa.org/home/wiki/Dev/Command-line/Dumps, but I figure it would need some more guidance to work through them. I'd be happy to work through them with you in another issue, or over IRC.

In the meantime, you can always continue to request them on demand. I can't promise to turn it around in a day, but I'll definitely try to get to it quickly.

> Will be installing Tibetan wiki soon, here: http://www.tcv.org.in/content/tcv-suja

Wow, that's great! Hope the kids find it useful. Keep in mind that XOWA allows you to edit the articles, so they can experiment with their wiking skills as well. ;)

Best of luck!

**Comment by cyberorg** [comment]
Yes for now we got everything desired, my coding skills extend only till shell scripting, I'll be in mountains till mid May, after that I'd be glad to help with any automation that can be done by scripting.

Thanks again.
