### ISSUE TITLE
Random "Obama everywhere"

### ISSUE THREAD

**Issue by jk273** [gnosygnu/xowa#141]
I am not sure, how to describe that, but when I open simple.wikipedia.org, pictures of Barack Obama are everywhere. I did find out, that pictures are stored here:
C:\wikipedia\file\commons.wikimedia.org\thumb\4\4\5\c\Obama_Madiba_Memorial.jpg (others in similiar folders)
But I have zero idea why they are there...

![obama1](https://cloud.githubusercontent.com/assets/12783872/24158415/911c854c-0e5c-11e7-9050-d8dca0d11a38.png)
![obama2](https://cloud.githubusercontent.com/assets/12783872/24158416/911fec82-0e5c-11e7-933e-e975ca98a5b3.png)

Additional info:
Windows 10 x64

Xowa x64
version: 	4.4.0.1703 (view changes)
build_date: 	2017-03-06 20:47:24 

After refreshing the pictures are still there (I will test restaring the Xowa after the import of enwiki is finished)

**Comment by gnosygnu** [comment]
Hi! Thanks for the screenshots and the great detail.

Unfortunately, I wasn't able to reproduce it now. I did the following:
* Launched XOWA
* On <code>home/wiki/Main_Page</code>, clicked the <code>Set up Simple Wikipedia</code> link
* After a few minutes, I got a screenshot like this: 
![simplewiki](https://cloud.githubusercontent.com/assets/4994104/24163415/e70199d2-0e40-11e7-938a-8b2979d76372.png)

Besides the Obama thumbnails, one thing that's very noticeable about your screenshots is that you have a lot of red links. For example <code>Roman god</code> and <code>Uranus</code> are redlinked in your screenshot but not mine. This indicates something is badly broken in the dump. I suspect that <code>simple.wikipedia.org/wiki/Roman_mythology</code> and <code>simple.wikipedia.org/wiki/Uranus</code> are missing from your wiki. (they exist in mine)

With that in mind, here are a few questions:
* Can you unzip a new XOWA 4.4 to a separate folder (C:\xowa_temp) and try importing Simple Wikipedia again? I want to see if the issue is reproducible on your side
* Have you ever changed the dump servers at <code>home/wiki/Special:XowaCfg?grp=xowa.bldr.general</code>? The first listed server is http://dumps.wikimedia.your.org but it's possible you picked up the bad dump from the other servers
* Have you ever turned on page sync at <code>home/wiki/Special:XowaCfg?grp=xowa.bldr.page_sync</code>. It's off by default, but it's possible that if you turned it on, you might have picked up a bad copy from the sync. (note that I turned it on right now, and it also works)

If all the above is no, copy and paste the HTML for the page here, and I'll see if I can figure anything out from it. You can get the HTML by clicking on the <code>View HTML</code> link near the upper right corner.

Hope this helps.

**Comment by jk273** [comment]
Hi,

I could not reproduce the error (with new XOWA and again import Simple wikipedia).  I have not turned on page sync or changed the dump servers. I guess it was really just a random glitch. It is probablly safe to conclude (and close the issue), that it was a one time error.

**Comment by gnosygnu** [comment]
Ok. Thanks for the follow-up. It does sound like it is a broken dump. If you still have the original one around you can compare the bz2 file size against https://dumps.wikimedia.org/simplewiki/20170320/

I've seen broken dumps while downloading, but literally something like 2 or 3 over 5 years. If this occurs more frequently, I'll put in a double-check for it. Otherwise, I'm going to hope this is a rare outlier.

Thanks again for the report.
