### ISSUE TITLE
[convert: invalid number]

### ISSUE THREAD

**Issue by khanhhung2512** [gnosygnu/xowa#142]
At en.wikipedia.org/wiki/Ethanol, in the chart on the right, under "Melting point" and "Boiling point", it says "[convert: invalid number]".

**Comment by gnosygnu** [comment]
Hi! Thanks for the report.

This is actually an issue with the XOWA parser, and I believe it's been there for some time. I'm going to guess it's happening now, because https://en.wikipedia.org/wiki/Module:Convert has changed sometime recently.

I wasn't able to get this fixed for tonight's release. In fact, I don't know if an easy fix is possible. It's definitely a high-priority issue for me, so I should have a better idea of what needs to be done in the next few days. I'll update then.

In case you're interested, this can be fixed on a case-by-case basis by editing the Wikitext to remove the &lt;ref>. Specifically, you'd have to change this:

> | MeltingPtC = −114.14 ± 0.03&lt;ref name=crc2/>

... to this ...

> | MeltingPtC = −114.14 ± 0.03

Anyway, I'll try to have better news in a few days.

Thanks.

**Comment by gnosygnu** [comment]
Ok. I think I have a fix for this issue. I uploaded a BETA release now if you want to give it a test: https://github.com/gnosygnu/xowa/releases/tag/v4.5.1.1703

Keep in mind this change doesn't affect compiled HTML databases (Download Central wikis). I think you work with Wikitext ones (Import online / offline), but I just want to be clear for any other users who happen on this issue.

Also, I'm working on a few other minor parser issues, so it may be a week or two before I get another official build out. In the meantime, I'm going to mark this issue resolved. Once the release goes out I'll close it out.

Let me know if there is anything else.

Thanks!

**Comment by khanhhung2512** [comment]
Yeah, it works. Btw, I'm still wondering if there're any ways to read articles not yet created at the time of import.

**Comment by gnosygnu** [comment]
> Yeah, it works. 

Cool. Thanks for the confirm.

> Btw, I'm still wondering if there're any ways to read articles not yet created at the time of import.

While working on personal wikis last month, I added a few features that makes it possible. It still needs a bit more work, but I'll try to get it into a near release.

**Comment by gnosygnu** [comment]
I'm still working on the auto-create of new pages, and am going to be tracking that under #144

Otherwise, the parser error was officially fixed in tonight's release. I'm going to mark this ticket closed accordingly. Thanks.
