### ISSUE TITLE
Add support for Special:CategoryTree (Bug Reports)

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#156]
This will be the place where I'm going to report every single bug that I may encounter. That being said, let's move on:

<>I'm not sure if this is a bug at all, but if you compare en.wikipedia.org/wiki/Portal:1970s to the online version you will see a big difference. Under "Categories" it should've shown "1970" 1971" etc. in XOWA. Same goes for en.wikipedia.org/wiki/Portal:1950s.
fr.wikipedia.org/wiki/Portail:Années_1940 as well. I think all other/some portals are affected by this.

**Comment by gnosygnu** [comment]
Hey, thanks for the report. If you don't mind, I'd rather have each issue be about one bug report, instead of having multiple bug reports in one. It makes tracking easier.

As for this issue, the items are missing because they're created by an extension which XOWA doesn't support: https://www.mediawiki.org/wiki/Extension:CategoryTree

I'd like to support it one day, but it has a lot of code (particularly on the Javascript side), so it may be a while. It will be at least several months, so I'll probably end up closing this issue and reopening whenever I address it.

Thanks.

**Comment by Ope30** [comment]
> Hey, thanks for the report. If you don't mind, I'd rather have each issue be about one bug report, instead of having multiple bug reports in one. It makes tracking easier.

Sure thing! I will always make a new issue.

> As for this issue, the items are missing because they're created by an extension which XOWA doesn't support: https://www.mediawiki.org/wiki/Extension:CategoryTree

> I'd like to support it one day, but it has a lot of code (particularly on the Javascript side), so it may be a while. It will be at least several months, so I'll probably end up closing this issue and reopening whenever I address it.

Oh. That sounds interesting. Okay then, I understand!

**Comment by gnosygnu** [comment]
Cool. Thanks!

**Comment by gnosygnu** [comment]
This issue is tagged as future enhancement. I'll reinvestigate it in the future someday, but for now, I'm going to mark this issue closed.

Thanks.
