### ISSUE TITLE
Double Image Description

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#160]
On some images it shows Double Description: https://image.prntscr.com/image/PW3pSaCDS2uTN17NDbbfmQ.jpeg
de.wikipedia.org/wiki/Philipp_von_Belgien_(1837–1905)

Is this a bug?

**Comment by gnosygnu** [comment]
Thanks for the screenshot.

Actually, this is by design. XOWA shows the [alt text](https://en.wikipedia.org/wiki/Wikipedia:Alternative_text_for_images) underneath the caption.

Sometimes it has more text which is nice to see on screen. For example, https://en.wikipedia.org/wiki/Earth and "Diagram showing the magnetic field lines of Earth's magnetosphere. The lines are swept back in the anti-solar direction under the influence of the solar wind."

Other times, as in your case, it's a duplicate (or near-duplicate)

If you use the wikitext databases, then you can turn this behavior off by unchecking "Alt text" -> "Show in Caption": home/wiki/Special:XowaCfg?grp=xowa.html.page

If you use the html databases, then there's no direct way to control this behavior. I'll try to add a config or CSS class to control this behavior in the future.

Hope this helps.

Thanks.

**Comment by gnosygnu** [comment]
For tonight's release, I added an option to always hide the duplicate alt in caption. See home/wiki/Special:XowaCfg?grp=xowa.html.page
