### ISSUE TITLE
Category: attach table limit causes [SQLITE_ERROR] SQL error or missing database (no such database: link_db_12) (attach table limit)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#268]
I have been rummaging around the display of categories logic (eg en.wikipedia.org/wiki/Category:Anarchism) and have noticed that a big sql statement is generated to combine all the category link database files together by using attach table.
For en.wikipedia 2018-06, there are currently 11 files with xtn.category.link-db in their name
The logic opens the first link file and then proceeds to attach the others

Unfortunately most Sqlite implementations have a fixed limit of 10 attached tables.
Special builds of Sqlite are required to overcome this limit (although the max is supposed to be 62)
[Sqlite uses a long word (64) bit table (main and temp take the first 2 hence 62)]

I wanted to do a further join to the cat_core table (but cant)

It is entirely possible with the growth of en.wikipedia that the number of categories tables will increase.

I see two choices
1)  get a special Sqlite build allowing more attached tables (non trivial)
2) increase the file size of each individual link file (this may have file storage implications)

What do you think?

**Comment by gnosygnu** [comment]
Ugh, nice catch. I never noticed that. (I copy-pasted the info below for reference later)

I agree that building a special SQLite binary is not desirable. I've had problems with the generic SQLite binary on Raspberry PI, and don't want to complicate things by forcing a custom version there (as well as other platforms).

As a temporary workaround, I think increasing the file size is best. I'll probably increase the limit to 3.6 GB here: https://github.com/gnosygnu/xowa/blob/341d2e13a43bb91e40b0c0204a750a5f56780a26/400_xowa/src/gplx/xowa/apps/apis/xowa/bldrs/imports/Xoapi_import.java#L20

As an FYI, it can also be increased by adding the following line to the bottom of xowa.gfs and launching the XOWA app

```
xowa.api.bldr.wiki.import.cat_link_db_max = 3600; // in MB
```

For a long term solution, I will probably end up rewriting Xoctg_catlink_loader so that it ATTACHes in groups of 10, rather than all at once. I chose a 1.5 GB limit b/c Sqlite has an unofficial 2 GB limit on Android. (It's officially 4 GB, but I couldn't get any file greater than 2 GB to work). However, since XOWA Android doesn't really support Categories (it works in theory, but I never tested it b/c it would require another 15+ GB of space), this probably won't need to happen for a while.

----

https://www.sqlite.org/limits.html

```
Maximum Number Of Attached Databases

The ATTACH statement is an SQLite extension that allows two or more databases to be associated to the same database connection and to operate as if they were a single database. The number of simultaneously attached databases is limited to SQLITE_MAX_ATTACHED which is set to 10 by default. The maximum number of attached databases cannot be increased above 125.

The maximum number of attached databases can be lowered at run-time using the sqlite3_limit(db,SQLITE_LIMIT_ATTACHED,size) interface.
```

**Comment by gnosygnu** [comment]
Sorry about the long wait. I replaced the UNION with a sequential load from each catlink database. Much more information in the comments here: https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/xowa/addons/wikis/ctgs/htmls/catpages/dbs/Xoctg_catlink_loader.java#L216

---

* en.wikipedia.org/wiki/Category:All_stub_articles
* en.wikipedia.org/wiki/Category:20th-century_American_male_actors
* en.wikipedia.org/wiki/Category:Bicycles
* en.wikipedia.org/wiki/Category:2001_albums
