### ISSUE TITLE
Rules based collator

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#269]
When I was reviewing the collation logic as part of the investigation of #237 
I came across the class file Uca_collator__icu__4_8.java
The logic does work - it just seems to me to be a bit unclear
My branch rule-based-collator is my attempt at clarity (or obscurity!)
 
I hope you dont mind the presumption.

**Comment by gnosygnu** [comment]
No worries: no presumption involved. :)

I do agree the code is a bit indirect. When I wrote it, I think I was as pessimistic as possible and only casted to RuleBasedCollator if numeric-sorting was true (which, if I recall correctly, only occurs for a minority of cases). I guess I was worried that Collator.getInstance may return something that is not a RuleBasedCollator and that this would cause an unnecessary failure even when numeric_sorting is false (i.e.: numeric_sorting can be false, and the code will still try to cast to RuleBasedCollator and throw an error even though this cast is not needed)

That said, it looks like RuleBasedCollator is the only subclass: http://icu-project.org/apiref/icu4j/com/ibm/icu/text/Collator.html . Still, I'd like to keep the pessimistic version since pessimism is at least safe.

Would it help if I add a comment to the effect of the below?:

```
if (numeric_ordering) {
  // NOTE: delaying cast to RuleBasedCollator b/c Collator.getInstance may return a non-RuleBasedCollator and don't want cast to fail if numeric_ordering is false 
  ((RuleBasedCollator)collator).setNumericCollation(true);
}
```

----
direct link to rule-based-collator change: https://github.com/desb42/xowa/commit/f0b8f538499d1b68ccf9af948f0af87e96d47358

**Comment by desb42** [comment]
Yes I think that is clearer.

Do I close this or do you?

**Comment by gnosygnu** [comment]
Oops. Forgot about this. Pushed commit now. Thanks!
