### ISSUE TITLE
shortcut icon

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#285]
In xowa.gfs (amongst other things) there are three html page templates
page_read, page_edit and page_html
they each contain a link of the form
`<link rel="shortcut icon" href="...">`
page_read href is `~{app_root_dir}bin/any/xowa/file/app.window/app_icon.png` which exists
page_edit and page_html href is `~{app_root_dir}user/anonymous/app/img/window/chrome/xowa.png` which does not exist

Having replaced the page_edit and page_html href with that of page_read, I don't get a web server error any more

**Comment by gnosygnu** [comment]
Thanks. I pushed the fix now.

On a related note, it looks like "View HTML" doesn't work in HTTP_Server. It's using old logic to try to get the html from the SWT browser: https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/xowa/htmls/Xoh_page_wtr_wkr.java#L62

I'm tracking the issue here: #288
