### ISSUE TITLE
lua getBestStatements does not work correctly

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#297]
I have been rummaging around (again) and come across the Template:Authority_control
(eg en.wikipedia.org/wiki/James_Monroe)
This calls Lua Module Authority_control
Within the depths of this module is a call to getBestStatements

This is where things get confused (for me)

In https://www.mediawiki.org/wiki/Extension:Wikibase_Client/Lua is the definition for getBestStatements

> <strong>wikibase.getBestStatements( entityId, propertyId )</strong>
Returns a table with the "best" statements matching the given property ID on the given entity ID. The definition of "best" is that the <em>function will return "preferred" statements, if there are any, otherwise "normal" ranked statements</em>. It will never return "deprecated" statements. This is what you usually want when surfacing values to an ordinary reader.

The italics are mine

`getBestStatements` is handled by Scrib_lib_wikibase.java which in turn calls `getEntityStatements` in  Wbase_entity_accessor.java. This logic does not follow the definition above

The logic as I see it should be do two scans of the Wbase_claim_grp statements
1) to look for preferred statements
2) look for normal

In other words first the preferred statements (if any) then the normal statements.
(see my branch getbest)

However there seems to be an even more fundamental issue
That is, what actually gets returned.
From what I can understand of the code, what gets returned are a list of 'values'
I believe that this function should be returning structured data.

In the Lua module Authority_control is the function

    function p.getIdsFromWikidata( itemId, property )
    	local ids = {}
    	local statements = mw.wikibase.getBestStatements( itemId, property )
    	if statements then
    		for _, statement in ipairs( statements ) do
    			if statement.mainsnak.datavalue then
    				table.insert( ids, statement.mainsnak.datavalue.value )
    			end
    		end
    	end
    	return ids
    end

the code `if statement.mainsnak.datavalue then` implies (to me) that getBestStatements returns 'structured' data.
I cannot work out what is going on

The real enwiki entry shows
![ac_wiki](https://user-images.githubusercontent.com/861631/49377042-feb2ee00-f700-11e8-97e2-fa8cf77559f6.jpg)
and xowa
![ac_xowa](https://user-images.githubusercontent.com/861631/49377062-083c5600-f701-11e8-8cfd-56a6b6b179b7.jpg)
No Authority control at all

[the wiki entry also has an additional portal 'International relations' which has been added since my dump]

**Comment by gnosygnu** [comment]
Hey, thanks for the detailed write-up.

Three points. Broken up into sections below.

#### You're right about the preferred/normal logic.
* XOWA incorrectly adds preferred only. If only normal exists, it doesn't add.
* However, I think your branch will always add preferred AND normal: https://github.com/desb42/xowa/commit/59509891bd7d15f96b8eea32a8aaf8d721beb140
* Instead, I think it should be "add preferred; if no preferred found, then add normal"

#### Authority control doesn't show because I think wikidata changed the logic recently.
* The offending line is line 172 in /xowa/bin/any/xowa/xtns/Scribunto/engines/LuaCommon/lualib/mw.wikibase.lua
```
if statements and statements[propertyId] then
```
* To fix it, change the following line: https://github.com/gnosygnu/xowa/blob/070eb3c53a237ede63f610e153bc63f20817281a/400_xowa/src/gplx/xowa/xtns/scribunto/libs/Scrib_lib_wikibase.java#L193
```
return rslt.Init_obj(Keyval_.new_(String_.new_a7(propertyId), Scrib_lib_wikibase_srl.Srl_claims_prop_ary(prop_mgr, String_.new_u8(propertyId), statements, 1)));
```
I'll put up a commit plus tests sometime this weekend

#### Finally, some hacky instructions for debugging luaj in XOWA
* Go to en.wikipedia.org/wiki/Module:Authority_control?action=edit
* Ctrl+F and "mw.wikibase.getBestStatements"
* Add the following dbg line
```
	if statements then
dbg(itemId, property, mw.dump_table(statements));
		for _, statement in ipairs( statements ) do
```
* Go to en.wikipedia.org/wiki/James_Monroe?action=edit
* Change the wikitext so it just reads this
```
{{Authority control}}
```
* Press preview -> You'll see debug statements in red

I couple the above with breakpoints in Java code to troubleshoot Scribunto issues. Even then, it takes me 30 min to 60 min to figure out what's going on (as it did tonight)

Hope this helps

**Comment by desb42** [comment]
Great - that works

Hours of debugging for a single line change - that about sums it up

**Comment by gnosygnu** [comment]
> Hours of debugging for a single line change - that about sums it up

Actually, discovered a 2nd bug. Was always using index 0: https://github.com/gnosygnu/xowa/blob/070eb3c53a237ede63f610e153bc63f20817281a/400_xowa/src/gplx/xowa/xtns/wbases/mediawiki/client/includes/dataAccess/scribunto/Wbase_entity_accessor.java#L60

Also, ended up changing a bunch of files just to add the new tests.

Anyway, commit pushed. Thanks again for the report!
