### ISSUE TITLE
link to toollabs incorrect

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#298]
I was looking at en.wikipedia.org/wiki/Scafell_Pike
Top right of the article has a coordinate that can be clicked that takes you to wmflabs.org
If clicked this will go to the site and then get an error
![labs_err1](https://user-images.githubusercontent.com/861631/49683236-21eeec00-fab9-11e8-9c53-c2565d74e346.jpg)
The reason for this error is the extra characters highlighted in red
xowa is adding `/wiki/` to the link

The code responsible for this is in Pfunc_urlfunc.java - `/wiki/` is being added to every link.
Most of the time thats OK; however not for wmflabs (and others?)
My 'fix' is to check for a domain.tid of 'other' and decide to apply 'wiki' or not
see my branch fullurl
This feels a bit clunky

**Comment by gnosygnu** [comment]
Cool. Thanks for the background and the commit link (https://github.com/desb42/xowa/commit/78428aa0c76cece2aa116843e94e1a13f99ba8c8)

I think your code is actually the best option for now. XOWA's version of getUrlFunction is quite divergent from https://github.com/wikimedia/mediawiki/blob/master/includes/parser/CoreParserFunctions.php#L258 .

I pushed your change now with a minor tweak (if wiki == other instead of if wiki != other)

Let me know if there is anything else. Thanks!
