### ISSUE TITLE
Id_xowa_wikidata* usage

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#348]
I was having a rummage (as I does) and came across the message keys/codes that start with Id_xowa_wikidata
As far as I can tell (AFAICT) these message are not used in the system
If not there is a potential tidy up in the language gfs files

Or am I wrong?

**Comment by gnosygnu** [comment]
Yup, it wasn't obvious to me either. :sweat:

In fact, it turns out that I actually do need these Id_xowa_wikidata items. Some unit-tests fail without them. :cold_sweat: This isn't good design, but it's a bit painful to change now.

I'm going to leave it as is and added a comment explaining the purpose. Will refactor in future, but it will probably be a while. Let me know if it's an eyesore.

Thanks.

**Comment by desb42** [comment]
This was more of an observation than anything else - I am happy to live with it

**Comment by gnosygnu** [comment]
Cool. Thanks. Will close out issue.
