### ISSUE TITLE
fsdb.main/fsdb.bin.0116.sqlite3 appearing again ?

### ISSUE THREAD

**Issue by markusmaresch** [gnosygnu/xowa#35]
Not a major concern - only a question.
With the latest update for en.wikipedia.org in file Xowa_enwiki_2015-12-06_file_v1.7z
I saw the 'old' (image ?) data base under 'file/*/fsdb.main' appearing again.
Is this correct and needed ?  It seems like an update - don't have fsdb.main.0001...0115.sqlite3 though.
I did not have a 'file' directory any more and added it - everything works just fine after adding this now.
thanks
Markus

![xowa_file_fsdb](https://cloud.githubusercontent.com/assets/13298571/12053110/0dd2c3f0-af16-11e5-9ae0-e4396354ee56.png)

**Comment by gnosygnu** [comment]
Thanks for the image. Nope, 116 was a mistake. That was an error in my packaging script. I'll leave the .7z file as is, but it could be 1.3 GB smaller. Sorry!

**Comment by markusmaresch** [comment]
Ok, thanks. So, I can delete the fsdb.main directory again - correct?

**Comment by gnosygnu** [comment]
Hey, I reread your original comment, and it seems like you only have v2b. Sorry about that. If so, you can delete the files in v1 (fsdb.main)

See below for more info.

Let me know if there's anything else. If not, then happy new year!

----

I uploaded two updates for English Wikipedia:

- v1: These are .sqlite3 files for users who are still using the original format and haven't transitioned to the new v2 format. These files will go into /xowa/file/en.wikipedia.org/fsdb.main
- v2b: These are .xowa files who have downloaded the latest format. These files go into /xowa/wiki/en.wikipedia.org

I had a user on v1 ask for an update, so I generated one for them. Otherwise v2b is what I regularly update as they have the compatible format for Android.

**Comment by markusmaresch** [comment]
Ok - thanks for the clarification. I have removed the fsdb.main directory and everything still seems to work.
