### ISSUE TITLE
enwiki html build not completing

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#360]
I set out to build the html pages of enwiki a few days ago.
Today, the process still has not finished but the last line on the console reads:

    done=8575000 left=1351 rate=37 time_past=2:15:28:46 d time_left=36 s mem_tot=15036055552 mem_free=6036939072
(the mem_tot/mem_free entries are additional logging that I added)

It is now 08:00 11/02/2019 (all timestamps are dd/mm/yyyy)

Looking at the session.txt timestamp 11/02/2019 00:58

The directory listing for the tmp working directory is

     Directory of G:\xowa\wiki\en.wikipedia.org\tmp\xomp
    
    11/02/2019  03:15    <DIR>          .
    11/02/2019  03:15    <DIR>          ..
    11/02/2019  03:13            40,055 xomp.perf.csv
    11/02/2019  03:14                 2 xomp.semaphore.uid.txt
    11/02/2019  03:15       421,568,512 xomp.sqlite3
    11/02/2019  03:14    <DIR>          xomp_000
    11/02/2019  03:15    <DIR>          xomp_001
    11/02/2019  03:14    <DIR>          xomp_002
    11/02/2019  03:15    <DIR>          xomp_003
    11/02/2019  03:14    <DIR>          xomp_004
    08/02/2019  14:39    <DIR>          xomp_005
    11/02/2019  03:14    <DIR>          xomp_006
    11/02/2019  03:14    <DIR>          xomp_007
                   3 File(s)    421,608,569 bytes
                  10 Dir(s)  3,488,765,181,952 bytes free
xomp_005 stands out

Looking at xomp.sqlite3 and table xomp_wkr shows

    0 2 20190211_031455 1228351 225555
    1 2 20190211_031525 1180000 225699
    2 2 20190211_031418 1235000 225524
    3 2 20190211_031552 1233000 225564
    4 2 20190211_031408 1228000 225384
    5 1 20190208_145304   22000  10754
    6 2 20190211_031408 1226000 225472
    7 2 20190211_031443 1223000 225490
It looks like worker 5 is in trouble (probably a loop)

If I break out (crash the process), can I continue or are there things not wrapped up?

**Comment by gnosygnu** [comment]
> If I break out (crash the process), can I continue or are there things not wrapped up?

You can resume, but it takes extra steps. See https://github.com/gnosygnu/xowa/issues/334#issuecomment-455022763

Also, can you zip up xomp.sqlite3 and attach it here? I'd like to figure out which page caused the infinite loop. It's probably the one from ```SELECT Min(page_id) FROM xomp_page WHERE page_status = 0;```

Finally, are you building 2019-01 or 2019-02? I'm going to build 2019-01 dewiki this week, and will probably also use 2019-01 for enwiki as well. Just want to compare apples to apples

**Comment by desb42** [comment]
by subtracting all the accessible xomp_00? sqlite databases (0,1,2,3,4,6,7) page_ids from xomp.sqlite3
I got 23000 rows
Which makes sense to me.
xomp_005 as shown in the xomp_wkr table has 22000 entries
So I assumed,
1) the page_ids are processed in order
2) the last 1000 entries contain the problem page_id

I then matched up those 1000 page_ids to page titles and fired them at my xowa webserver
on the 257th hit my server got an unterminating thread - found something!

The offending entry is page `Gasket`
The code causing the problem is

    {{ubl
    |1. [[o-ring]]
    |2. fiber [[Washer (mechanical)|washer]]
    |3. paper gas
    |4.=4. [[cylinder head]] [[head gasket|gasket]]}}
Within that, I guess that the `4.=4.` is the offender (probably the equals sign)

Mediawiki just ignores the line

**Comment by gnosygnu** [comment]
Wow! Thanks! That's quite a bit of detective work!

My bad on the ```SELECT count(*) FROM xomp_page WHERE page_status != 0```. I think that statement needs to be run after xomp_resume is run. I believe xomp_resume automates the ```by subtracting all the accessible xomp_00? sqlite databases (0,1,2,3,4,6,7) page_ids from xomp.sqlite3``` 

I looked at it quickly this morning, and I'm guessing it's a LuaJ error. A little more details below. I'll try to fix it soon, but it may very well not happen until the weekend. If it is LuaJ, then these errors are pretty hard to track down. Will let you know.

Thanks!

----

Above snippet can be reduced to the following:

```
{{ubl
|1.
|2.=a}}
```

Which can be run from any page (I'm running on en.wikipedia.org/wiki/Wikipedia:Sandbox?action=edit)

The problem is this part in https://en.wikipedia.org/wiki/Module:List

```

for listType in pairs(listTypes) do
	p[listType] = function (frame)
		local mArguments = require('Module:Arguments')
		local origArgs = mArguments.getArgs(frame)
		-- Copy all the arguments to a new table, for faster indexing.

-- gnosygnu: iterating origArgs causes freezing
-- comment the dbg line, and it no longer freezes (but just returns 'abc')
dbg(mw.dump_table(origArgs));
		local args = {}
--		for k, v in pairs(origArgs) do
--			args[k] = v
--		end
--		return p.makeList(listType, args)
return 'abc'
	end
```

Note that the sample shows that calling pairs on origArgs (or doing any other iteration of origArgs) causes the lock-up

https://en.wikipedia.org/wiki/Module:Arguments looks very complicated, and it'll take me a while to figure out what it's doing....

**Comment by gnosygnu** [comment]
I was able to track down the problem. It is in LuaJ, and I should have a fix by the weekend. Let me know if you want a dirty fix earlier, and I'll push something out tonight.

More details below if you're curious. Thanks

---

I was able to reduce Module:Arguments to this Scribunto script

```
local p={}

local args, metaArgs, nilArgs, metatable = {}, {}, {}, {}
setmetatable(args, metatable)
metaArgs[1] = 'a';
metaArgs[2] = 'b';

local function translatenext(invariant)
  local k, v = next(invariant.t, invariant.k)
  invariant.k = k
  if k == nil then
    return nil
  else
   return k, v
  end
end
metatable.__pairs = function ()
  return translatenext, { t = metaArgs }
end

function p.test20(frame)
  for key, val in pairs(args) do
    dbg(key, val);
  end
end

return p
```

So, here's an easy way to reproduce it:
* Go to home/wiki/Module:Test
* Paste the script above and save it
* Go to home/wiki/Project:Sandbox 
* Paste this script and preview it. 
  * **Don't save it, else you will break your home.xowa**
```
{{#invoke:Test|test20}}
```
* This will output ```1 a``` and ```2 b``` in red
* Go back to home/wiki/Module:Test
* Change the following line: ```metaArgs['2.'] = 'b';```
* Go to home/wiki/Project:Sandbox and re-preview the script
  * XOWA will now lock up

The problem is this line in LuaJ and LuaTable.java

```
hash[index] = hash[index].set( foundSlot, value );
```

Because of the way this is set up, this will actually "cast" the ```2.``` string into a 2 int. This breaks the Scribunto script above. Specifically, the ```invariant.k = k``` breaks

```
-- pseudo-code
dbg(k);            -- outputs '2.' string
dbg(invariant.k);  -- outputs 2 int
invariant.k = k;
dbg(invariant.k);  -- outputs 2 int still; '2.' string assignment is ignored as '2.' string gets auto-cast to 2 int
```

Since invariant.k never changes, the loop remains the same and the code locks

The easiest way to fix this is to change NumberValueEntry.set in LuaTable.java to this line
```
if ( !n.isnil() && !value.isstring()) { // XOWA: HACK!
```

However, this is a hack, and it sits really deep in LuaJ code. Moreover, Lua has some loose-typing rules with ints as strings ``` '2' (string) -> 2 (int) '``, so this will probably break something else.

I have an idea how to handle it in the hash.set line above, but want to go through the code a little more closely.

**Comment by desb42** [comment]
That is also some detective work!
I have no issue with your proposed timescale - after all I have actually fix the problem wikitext in en.wikipedia.org/wiki/Gasket
Partly as a consequence of that (and slow broadband) I plan to download March 01 dumps and build the world from there
Meanwhile, I will continue with other investigations

**Comment by gnosygnu** [comment]
Cool. Thanks!

* I made the code changes in [the luaj repository](https://github.com/gnosygnu/luaj_xowa/commit/80082bea9e6bee3a8f734c29787c7ed86d704b91) 
* I commited the binary and the diagnostic test [here](https://github.com/gnosygnu/luaj_xowa/commit/80082bea9e6bee3a8f734c29787c7ed86d704b91)

Thanks again for all the initial work!
