### ISSUE TITLE
en:Portal:Germany takes a long time to load

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#365]
working with 2019-01-01 dump of enwiki, I have recently tried to build the html pages with issues documented elsewhere (#360, #351, #334 )
Various session.txt (and err.txt) files have been generated

Now I have stumbled across this page en.wikipedia.org/wiki/Portal:Germany
First of all this take over three minutes to build - every time
Second this generates two 'invoke failed' messages

to the first point, would it be useful (desirable) to keep track of how long it takes to build an individual page (as part of the html build)?
Also, an http-server request (via nginx) waits about 30 seconds before timing out - so this page generation takes way too long. 

on the second point, these errors did not show up in my full html build session logs - have you a view as to why that might be - or have I got it wrong again

**Comment by desb42** [comment]
I forgot to mention that on the real web site the wikitext has been updated significantly, so results would be different on later dumps

**Comment by desb42** [comment]
I have an answer to the second point
The wikitext includes some randomisation that could explain why it did not occur in the full build

This leads to  another concern about code coverage. Some errors may only occur due to this randomness - eek

**Comment by gnosygnu** [comment]
Sorry for the late reply on this. Answering your points above.

> to the first point, would it be useful (desirable) to keep track of how long it takes to build an individual page (as part of the html build)?

That's a great idea. It should be relatively simple, but I probably won't get around to it for a few weeks.

> Also, an http-server request (via nginx) waits about 30 seconds before timing out - so this page generation takes way too long.

Yeah, most pages are supposed to take about 10 or seconds, but I wouldn't be surprised if some take over 30 seconds. In my opinion:
* Scribunto is the cause of the delay. There can be a lot of code executing in the background and this will slow it down.
* Wikipedia is largely unaffected because (a) they have powerful servers; (b) the delay in generating the page is only bourne by the editors; afterwards it's cached for most viewers

I don't know of any way to make this less than 30 seconds except to fix performance bottlenecks. Unfortunately, performance optimization can be very time-consuming...

> on the second point, these errors did not show up in my full html build session logs - have you a view as to why that might be - or have I got it wrong again

Not sure I follow. Do you mean that the error message showed up in error.txt but not in session.txt? If so, that's weird. Maybe attach both and I'll take a look at it?

> The wikitext includes some randomisation that could explain why it did not occur in the full build
> This leads to another concern about code coverage. Some errors may only occur due to this randomness - eek

Yeah, I ran across this a long time ago when I saw that en.w:India was using random to show different pictures. And that was when only Templates were available. Not that there are Modules, there really is nothing I can do about this. The wikitext databases should still be an accurate reproduction of the Wikipedia experience, but the html databases can not be. At this point, I can only hope that the editors use randomization with discretion....

**Comment by desb42** [comment]
> Not sure I follow. Do you mean that the error message showed up in error.txt but not in session.txt?

To try to clear this up.
I ran a full html build of enwiki (which resulted in the build not completing #360 )
Due to the way it failed there where about 1000 pages not processed; however ~8Million were

I looked through the session.txt and err.txt with some care, to see if there were other issues needing review 
I was particularly focused on #invoke errors

There were no invoke errors for Portal:Germany in these logs
(it is just possible that this page was one of the 1000 that were not processed)

**Comment by gnosygnu** [comment]
> There were no invoke errors for Portal:Germany in these logs
> (it is just possible that this page was one of the 1000 that were not processed)

Yeah, I'd guess it was the latter. XOWA proceeds sequentially through namespaces and page ids. Portal is namespace 100 and it would be one of the last ones (The order is 0|4|14|100|8)

I'm working on two issues with dewiki and the htxt dump which I hope to have done this weekend. Afterwards, I'll give enwiki a try

**Comment by desb42** [comment]
To answer my own question about why the #invoke errors do not show up - I am not including namespace 100 in my html_dump

**Comment by gnosygnu** [comment]
Cool. That also explains why you didn't run into the problems I did for #413. I'm trying to fix it now, but it's a doozy...

**Comment by gnosygnu** [comment]
I'm going to mark this item resolved, as it's handled by #413 . Just one point

>> to the first point, would it be useful (desirable) to keep track of how long it takes to build an individual page (as part of the html build)?

> That's a great idea. It should be relatively simple, but I probably won't get around to it for a few weeks.

Well, it turned out to be complicated, but I've been working on stats in order to troubleshoot #413. I'll make a separate issue / commit for this sometime tomorrow.
