### ISSUE TITLE
timeline.js needs some updates

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#368]
Over the last couple of weeks I have been working on timeline.js

This is a remarkable piece of work by Schnark that needs a little updating

I know that mediawiki uses a pipeline of processes to build the timeline (using Easytimeline.pl and ploticus)
However timeline.js does a very good equivalent

\<timeline> is used roughly 10,000 times in approx 8,000 main pages
In the Template namespace 1,200 times in approx 400 templates

tag:timeline is used 2,300 times in 1,800 main pages
and in the Template namespace 70 times in 70 pages

All numbers are approximates

It does show that there is still considerable use, given mediawiki's desire to migrate all these to \<graph>

I have been randomly selecting timelines and been comparing the xowa and mediawiki products

I am not able to get exact equivalence but it is pretty good

The fixes I have found so far are: 

* multiple links
https://en.wikipedia.org/wiki/Template:Timeline_WWII_-_Pacific_Theater

* horizontal axis
https://en.wikipedia.org/wiki/1910_Atlantic_hurricane_season

* multiline (collapsed) legend
https://en.wikipedia.org/wiki/42-01
https://en.wikipedia.org/wiki/The_Beach_Boys#Members

* legend start position
https://en.wikipedia.org/wiki/42-01

* vertical scale
https://en.wikipedia.org/wiki/Solar_power_in_Alaska

* double quoted strings
* bar.shift offsets (merging) (-5) or (7,) or (,-4)
https://en.wikipedia.org/wiki/South_Eastern_Collegiate_Hockey_Conference
https://en.wikipedia.org/wiki/19th-century_National_League_teams

* remove leading and trailing \<p>\</p> (don't know how they get there!)

* if background colour to bars, don't colour the whole background
* draw markers (start and end)
https://en.wikipedia.org/wiki/Browser_engine

* draw horizontal bar marks
https://en.wikipedia.org/wiki/Mount_Hood_climbing_accidents

* need to override the order the bars if there are smaller ones they must be last
https://en.wikipedia.org/wiki/The_Beach_Boys#Members

* squash legend at 'bottom'
https://en.wikipedia.org/wiki/Kicking_Sunrise#Members
https://en.wikipedia.org/wiki/Lifespan_Timeline_of_Prime_Ministers_of_Romania

* With multiple Plotdata entries only resets anchor
https://en.wikipedia.org/wiki/Classical_antiquity

* draw slightly thicker lines
https://en.wikipedia.org/wiki/Disneyland_Paris#Attendance

* Defines are case insensitive
https://en.wikipedia.org/wiki/Canada–United_States_relations

* comment marker `#` is also used in [[links]], so need to be ignored (within quotes)
https://en.wikipedia.org/wiki/Template:NASA_Planetary_Missions_Program

* barset:break can have other data on the same line - code rearrangement required
https://en.wikipedia.org/wiki/Template:Space_station_crew_timeline

* No left hand axis
https://en.wikipedia.org/wiki/Template:NASA_Planetary_Missions_Program

* No bottom axis
https://en.wikipedia.org/wiki/1910_Atlantic_hurricane_season

* Axis bar can have a name and no data
https://en.wikipedia.org/wiki/History_of_Islam - first timeline

* PlotData Bar: can be blank
https://en.wikipedia.org/wiki/History_of_Islam - second timeline

* Need to keep track of Bar order (Bars with numeric value do not order correctly)
https://en.wikipedia.org/wiki/Tromborn

* colours should be case insensitive
https://en.wikipedia.org/wiki/Template:Space_station_crew_timeline

* adjust the link colour to be a closer match to mediawiki
* make the font bold
* adjust position of legend text in relation to the colour square

* subtle (ie guesses) changes to vertical alignment (bar versus barset)
https://en.wikipedia.org/wiki/Timeline_of_political_parties_in_the_United_Kingdom

* if a preset, scales are only used if defined after the preset
https://en.wikipedia.org/wiki/Hindu_units_of_time

An area of considerable difficulty is imagesize 'height:auto'
I cannot get the height calculation to match up and I can't see a pattern

https://en.wikipedia.org/wiki/Dinasaur - multiple plot areas and height:auto - ugh

Please see my timeline branch

**Comment by gnosygnu** [comment]
> This is a remarkable piece of work by Schnark that needs a little updating

Yup. I don't do PERL, but in my few visits to Easytimeline.pl, I was impressed by the breadth of his work.

> I am not able to get exact equivalence but it is pretty good
> The fixes I have found so far are:

Wow! Those are a lot of changes. I would say that's an impressive coverage of issues which rivals the original work.

I'll pull [the changes](https://github.com/desb42/xowa/commits/timeline) this weekend, and verify them with your links above. I'll also take a look at the Dinosaur problem -- to see if I have anything to offer.

Thanks!

**Comment by desb42** [comment]
In the timeline branch is a java change - to add an extra encompassing div
This div has a class of 'timeline-wrapper' 
The class has no definition in the xowa_wiki.css or xowa_common.css
(as these files are generated from looking at the Main_page during a full rebuild)

In this case the css needed is

    .timeline-wrapper {
        max-width: 100%;
        overflow: auto
    }

I have just tacked this onto the end of  /fsys/user/anonymous/wiki/en.wikipedia.org/html/xowa_wiki.css

given that mediawiki adds css dynamically - that is, depending on things in the page different css is triggered (timeline as a simple example)
Is there, should there, be a way of adding extra css

Apart from size of file, the css associated with all the extensions could be wrapped up in one css file

Unfortunately this also begs the question of the javascript associated with each wiki and the extensions

**Comment by desb42** [comment]
Looking at #370 I happened to try de.wikipedia.org/wiki/Österreich
This has a \<timeline> in it and has shown up two further issues with timeline.js

The text is now vertically align using 'alphabetic' and any text line that is outside the image (or lying right on the edge (vertically)) is 'forced' into the image - I am hoping this works for all situations

I have made changes to the timeline branch to reflect this

**Comment by gnosygnu** [comment]
Again, I got to say, "Wow!" I went through each of the links and I'm really impressed that you were able to resolve so many (much less, identify in the first place) Many thanks again!

In the end, I did the following:
* Reviewed the "before" and "after" for each of the links. I'll post a table in the next comment
* Spot-checked some of the javascript changes (most of them require a deeper understanding of timeline.js which I don't have)

Finally, I added jasmine and made the timeline unit-testable. 
* Changed everything from ```function functionName``` to ```this.functionName = new Function```
* Invoked functions with ```self.functionName``` instead of ```functionName```
* Changed timeline.js to assign ```timeline``` reference to ```window.xowa.timeline```

I added some unit-tests as an example. You can run ```timeline.test.html``` in a browser. This is more of an experiment on my side, as I've wanted to have unit-testing on the Javascript side (there are over 5 thousand for XOWA). Feel free to ignore them or whatever.

Anyway, let me know if there is anything else. And again, even though it is repetitive to the point of obviousness, let me say "Thanks again!".

**Comment by gnosygnu** [comment]
Issue | Reviewed | Page
----- | -------- | ----
? multiple links | ??? | https://en.wikipedia.org/wiki/Template:Timeline_WWII_-_Pacific_Theater
horizontal axis | x-axis missing | https://en.wikipedia.org/wiki/1910_Atlantic_hurricane_season
multiline (collapsed) legend | legend 1 column instead of 2 rows | https://en.wikipedia.org/wiki/42-01
^ see above | legend 1 column instead of 2 rows | https://en.wikipedia.org/wiki/The_Beach_Boys#Members
legend start position | legend overlaps with y-axis; legend | https://en.wikipedia.org/wiki/42-01
vertical scale | y-axis littered with multiple marks | https://en.wikipedia.org/wiki/Solar_power_in_Alaska
double quoted strings | title has quotation marks | ^ see below
bar.shift offsets (merging) (-5) or (7,) or (,-4) | last 5 bars run past right right edge of graph | https://en.wikipedia.org/wiki/South_Eastern_Collegiate_Hockey_Conference
^ see above | ??? | https://en.wikipedia.org/wiki/19th-century_National_League_teams
remove leading and trailing <p></p> (don't know how they get there!) | ???  |
if background colour to bars, don't colour the whole background | ???  |
draw markers (start and end) | background is no longer entirely gray | https://en.wikipedia.org/wiki/Browser_engine
draw horizontal bar marks | y-axis has red marks | https://en.wikipedia.org/wiki/Mount_Hood_climbing_accidents
need to override the order the bars if there are smaller ones they must be last | ??? | https://en.wikipedia.org/wiki/The_Beach_Boys#Members
squash legend at 'bottom' | ??? same as The_Beach_Boys? | https://en.wikipedia.org/wiki/Kicking_Sunrise#Members
^ see above| | https://en.wikipedia.org/wiki/Lifespan_Timeline_of_Prime_Ministers_of_Romania
With multiple Plotdata entries only resets anchor |  ?? vertical blue bookmarks around each gray bar | https://en.wikipedia.org/wiki/Classical_antiquity
draw slightly thicker lines| main graph line is thicker| | https://en.wikipedia.org/wiki/Disneyland_Paris#Attendance
Defines are case insensitive| links in blue boxes were not visible (Eisenhower) | https://en.wikipedia.org/wiki/Canada–United_States_relations
comment marker # is also used in [[links]], so need to be ignored (within quotes) | stray wikitext in bar; EX: ```[["Mars Express``` | https://en.wikipedia.org/wiki/Template:NASA_Planetary_Missions_Program
barset:break can have other data on the same line - code rearrangement required | ```Long-Duration Crews...``` missing | https://en.wikipedia.org/wiki/Template:Space_station_crew_timeline
No left hand axis | y-axis bar missing | https://en.wikipedia.org/wiki/Template:NASA_Planetary_Missions_Program
Axis bar can have a name and no data | x-axis missing ```Region``` title | https://en.wikipedia.org/wiki/History_of_Islam - first timeline
PlotData Bar: can be blank | Rashidun bar missing | https://en.wikipedia.org/wiki/History_of_Islam - second timeline
Need to keep track of Bar order (Bars with numeric value do not order correctly) | y-axis should be in descending order | https://en.wikipedia.org/wiki/Tromborn
colours should be case insensitive | remove random redquotes show up   | https://en.wikipedia.org/wiki/Template:Space_station_crew_timeline
adjust the link colour to be a closer match to mediawiki | confirmed | ^ see above 
make the font bold | confirmed | ^ see above 
adjust position of legend text in relation to the colour square | confirmed  | ^ see above 
subtle (ie guesses) changes to vertical alignment (bar versus barset) | legend aligned within bar |  https://en.wikipedia.org/wiki/Timeline_of_political_parties_in_the_United_Kingdom
if a preset, scales are only used if defined after the preset | x-axis black; legend unreadable | https://en.wikipedia.org/wiki/Hindu_units_of_time
