### ISSUE TITLE
Predefined groups for footnotes

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#382]
Looking at the page en.wikipedia.org/wiki/Help:Footnotes#Footnotes:_predefined_groups
I noticed that xowa did not show the correct superscripts (ie should be a,b only showing 1,2)
It took me a while to understand why the actual footnotes came out right (because the browser is doing it)

For the superscripting, I have put together some code to emulate this behaviour

First of all I moved Pfxtp_roman to its own class file (taken from Pft_func_time.java)
I then enhanced this class to give lower and uppercase roman numerals

I have added a new routine into Ref_html_wtr.java to cope with the various predefined groups

It is a little rough - I think the group names should have some form of key id and I don't know your naming conventions

These changes are wrapped up in my superscript branch
What do you think

**Comment by gnosygnu** [comment]
Thanks for [the code sample](https://github.com/desb42/xowa/commits/superscript). Will work on this Sunday morning and should have done by end of day.

**Comment by gnosygnu** [comment]
Sorry for the delay. I started off by including the above sample, but then came across edge cases (such as more than 26 alpha footnotes). I reviewed the MediaWiki Cite code and thought that doing it their way wouldn't be that hard. Two days later, I found out I was wrong, but at least I pushed the above commit

The change is "drastic" but it only affects super-scripting. I visually compared https://en.wikipedia.org/wiki/Help:Footnotes with XOWA and the two now match.

Let me know if there is anything else. Thanks again for the initial work, as it definitely did help me narrow the scope of investigation (particularly the mention of the CSS/counter rules for the other half of the references).

**Comment by desb42** [comment]
looks great - I'm still trying to understand your approach

**Comment by gnosygnu** [comment]
Yeah, the main part is the [new Cite_mgr](https://github.com/gnosygnu/xowa/commit/a94a9f0c7ff4c08462ae876a1e199a457067e37d#diff-c06b822e01724114d6e3fd09a178c88eR28). It's supposed to match the corresponding [MediaWiki Cite.php](https://github.com/wikimedia/mediawiki-extensions-Cite/blob/master/includes/Cite.php#L976). In the future, I'm going to try to move XOWA logic into Cite_mgr (so that there is a closer tie between MediaWiki code and XOWA code)

The rest of the commit is a lot of infrastructure support (primarily to support caching at a wiki level)

Closing issue for now. Feel free to reopen if anything else.  Thanks.
