### ISSUE TITLE
regx is invalid

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#383]
I have just tried to build enwitionary 2019-03-01
During the html build stage I get a lot of 
`regx is invalid: regx=([ক-হড়-য়ৰৱ]়?)([oা-ৌ’’\?্]?) page=...`

I stopped the html build, and just picked one of the pages en.wiktionary.org/wiki/dictionary
Using a new xowa build and the gui interface, the logs showed this error

    20190312_070335.822 regx is invalid: regx=([ক-হড়-য়ৰৱ]়?)([oা-ৌ’’\?্]?) page=dictionary exc=[err 0] <java.util.regex.PatternSyntaxException> Illegal character range near index 8
    ([ক-হড়-য়ৰৱ]়?)([oা-ৌ’’\?্]?)
            ^
    [trace]:
      java.util.regex.Pattern.error(Pattern.java:1957)
      java.util.regex.Pattern.range(Pattern.java:2657)
      java.util.regex.Pattern.clazz(Pattern.java:2564)
      java.util.regex.Pattern.sequence(Pattern.java:2065)
      java.util.regex.Pattern.expr(Pattern.java:1998)
      java.util.regex.Pattern.group0(Pattern.java:2907)
      java.util.regex.Pattern.sequence(Pattern.java:2053)
      java.util.regex.Pattern.expr(Pattern.java:1998)
      java.util.regex.Pattern.compile(Pattern.java:1698)
      java.util.regex.Pattern.<init>(Pattern.java:1351)
      java.util.regex.Pattern.compile(Pattern.java:1054)
      gplx.langs.regxs.Regx_adp.Under_sync(Unknown Source)
      gplx.langs.regxs.Regx_adp.Pattern_(Unknown Source)
      gplx.langs.regxs.Regx_adp.<init>(Unknown Source)
      gplx.langs.regxs.Regx_adp_.new_(Unknown Source)
      gplx.xowa.xtns.scribunto.libs.Scrib_lib_ustring.RegxAdp_new_(Unknown Source)
      gplx.xowa.xtns.scribunto.libs.Scrib_lib_ustring_gsub_mgr.Exec_repl(Unknown Source)
      gplx.xowa.xtns.scribunto.libs.Scrib_lib_ustring_gsub_mgr.Exec(Unknown Source)
      gplx.xowa.xtns.scribunto.libs.Scrib_lib_ustring.Gsub(Unknown Source)
      gplx.xowa.xtns.scribunto.libs.Scrib_lib_ustring.Procs_exec(Unknown Source)
      gplx.xowa.xtns.scribunto.procs.Scrib_proc.Proc_exec(Unknown Source)
In fact for that page there are three separate regx issues

Given my track record on this (#335) are you able to reproduce?

**Comment by gnosygnu** [comment]
Apologies for the lack of communications over the last several days. Got a stomach illness on Tuesday evening and have spent a few days recovering. Still a bit weak and will likely be slow in recovery

Spent an hour looking at this, and the problem is magnified by an invalid character range ```([ক-হড়-য়ৰৱ]়?)([oা-ৌ’’\?্]?)``` (the second range around the dash. I think there is an issue on the XOWA side and a bad assumption that one byte equals one char. Will fix this weekend.

**Comment by desb42** [comment]
Take all the time you need, it's only code

**Comment by gnosygnu** [comment]
> Take all the time you need, it's only code

Yup. Thanks for understanding.

> the problem is magnified by an invalid character range

So, this error came up fortuitously. It turns out the wikitext had an invalid character range: "[ড়-য়]" or 2492-2479

Mediawiki keeps only the first part. XOWA happened to keep the entire thing because it was reading one byte at a time and was comparing the last byte of the beginning codepoint with the first byte of the ending codepoint. I'm sort of surprised that more things didn't break.

At any rate, I had to rewrite a lot of the regex converter to iterate by codepoints instead of bytes. Passed all tests and double-checked with en.d:dictionary as well.

Thanks again for the precise report. Also, no need to ever mention track record. I think you've more than proven it. ;)
