### ISSUE TITLE
the log should contain the full page name (including namespace)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#387]
Having rebuilt the html of enwiktionary, I am now reviewing the session log
One entry confused me

    20190318_170404.359 toc:invalid html; page=Etymology_scriptorium/2013/October src=<a href="/wiki/shaman#rfv-etymology-notice--" title="shaman"><p>shaman</a> 
I could not find `en.wiktionary.or/wiki/Etymology_scriptorium/2013/October`
However I could find `en.wiktionary.or/wiki/Wiktionary:Etymology_scriptorium/2013/October`
The page name should have the namespace
(This is a minor issue)

I am still investigating the actual error

**Comment by gnosygnu** [comment]
Cool, thanks for the details and sorry for the lazy on my side. (I used to just output page_title)

I added the page_url (wiki + page_namespace + page_title) to the logging calls. This involved changing a bunch of files, but the overall change was trivial. See commit above.

Regarding the error, this is a pretty one-off type of issue. The purpose of the Xoh_toc_wkr__txt (Xowa Table of Contents worker to generate text) is to strip any HTML from the header in order to generate a plain text version.

In this case https://en.wiktionary.org/wiki/Wiktionary:Etymology_scriptorium/2013/October has a caption of ```<a href="/wiki/shaman#rfv-etymology-notice--" title="shaman"><p>shaman</a>```. The unclosed ```<p>``` tag is confusing the Xoh_toc_wkr. I'm not sure how the ```<p>``` is generated since the wikitext is plain: ```[[shaman#rfv-etymology-notice--|shaman]]```. Let me know if you see a lot of these and I'll investigate. Thanks.
