### ISSUE TITLE
XOWA doesn't work on OS X

### ISSUE THREAD

**Issue by mikh3x4** [gnosygnu/xowa#39]
On running: `sh /Users/mik/Desktop/xowa_app_macosx_v3.2.1.1/xowa_macosx `
I get this output. I get the same issue with both 64bit and 32bit versions.
```
sh /Users/.../Desktop/xowa_app_macosx_v3.2.1.1/xowa_macosx 
Exception in thread "Thread-1" java.lang.UnsupportedClassVersionError: gplx/xowa/Xowa_main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```
On running `java -Xmx256m -d32 -XstartOnFirstThread -jar /Users/.../Desktop/xowa_app_macosx_v3.2.1.1/xowa_macosx.jar ` I get an identical output

I have tried installing an older version of Java from [here](https://support.apple.com/kb/dl1572?locale=en_US) Its worth noting that I'm doing this on a new mac running os x 10.11 which might not have the older versions of java installed. The `env | grep JAVA` command gives no output. This seam like an identical issue to [this one](https://github.com/gnosygnu/xowa/issues/18).

**Comment by gnosygnu** [comment]
Hi! Thanks for the detailed info, as well as the stack trace. A few notes:

* Unsupported major.minor version 51.0 specifically means that [java 7 is missing](http://stackoverflow.com/questions/10382929/how-to-fix-unsupp[orted-major-minor-version-51-0-error). This is because you have java 6 as you indicated above ("I have tried installing an older version of Java from here")
* I think you identified the problem correctly as a clean OS X 10.11. It looks like Apple no longer installs Java by default starting in OS X 10.11. You'll have to install it manually. See: http://osxdaily.com/2015/10/17/how-to-install-java-in-os-x-el-capitan/. The relevant excerpt is
    * Open a Terminal and type “java -version” then click the “More Info” button to jump to the Java downloads page
    * Or, go to the Java downloads page directly here on Oracle.com where you can find the JRE and the JDK
* You can also look at [this link](https://oliverdowling.com.au/2015/10/09/oracles-jdk-8-on-mac-os-x-el-capitan/). It says that installing the JDK might be quicker. It also gives an even more manual approach to [install the JRE](https://oliverdowling.com.au/2015/10/09/oracles-jre-8-on-mac-os-x-el-capitan/)

Let me know if neither of the above pan out, and I'll investigate further. At this point though, I think it's a matter of just getting Java on your system. Sort of a bummer that Apple makes it harder for Java apps, but unfortunately XOWA needs it. :(

**Comment by mikh3x4** [comment]
Installing the latest version of Java fixed the issue. I didn't even consider the fact that El Cap doesn't come with Java preinstalled (Seemed like such a no-brainer). Thanks for developing this awesome app! :D

**Comment by gnosygnu** [comment]
Great! Thanks for following-up! Glad to hear from another person satisfied with XOWA. :)

I'm going to close this ticket out for now. Let me know if there's anything related and I'll reopen. Thanks!
