### ISSUE TITLE
lua mw.ustring.gsub incorrect substitution

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#393]
I came across this snippet of wikitext from en.wiktionary.org/wiki/Wiktionary:Scripts

    {{#invoke:string|gsub|Blis, Cirt, Egyh, Hrkt, Latg, Moon, Nkgb, Qaaa, Qabx, Roro, Sara, Syre, Syrj, Syrn, Visp, Zinh, Zxxx|%u%l%l%l|<code>%1</code>}}
In mediawiki it produces
`Blis`, `Cirt`, `Egyh`, `Hrkt`, `Latg`, `Moon`, `Nkgb`, `Qaaa`, `Qabx`, `Roro`, `Sara`, `Syre`, `Syrj`, `Syrn`, `Visp`, `Zinh`, `Zxxx`
xowa produces
`%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`, `%1`

oops?

I would guess at `<code>%1</code>` causing the problem

**Comment by gnosygnu** [comment]
Yeah, oops. In my defense, this was a relatively recent change. The [actual lines](https://github.com/wikimedia/mediawiki-extensions-Scribunto/blob/master/includes/engines/LuaCommon/UstringLibrary.php#L785-L796) are worth highlighting.

```
} elseif ( $x === '1' ) {
    // Match undocumented Lua string.gsub behavior
   return $m[0];
} else {
```

Fixed with the commit above.

Thanks for the clean write-up (as always).
