### ISSUE TITLE
templatestyle and .mw-parser-output

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#426]
#274 suggests adding an extra div with class "mw-parser-output" to bring it in line with mediawiki

When I compare the templatestyle output between xowa and mediawiki there are (at least) two noticeable differences

1) mediawiki is compress (any comments and unnecessary space are removed)
2) all selectors have an additional class .mw-parser-output

There is a third issue to do with any url() entry as the appropriate image needs to be redirected to local storage

A suggestion is that during the build phase, an extra process be added that goes through the Template namespace and finds and replaces all *.css entries with a compressed, mw-parser-output and url change. (done as a 'user' edit)

A bit like the css work done in 'text.css' phase

**Comment by gnosygnu** [comment]
> #274 suggests adding an extra div with class "mw-parser-output" to bring it in line with mediawiki

Thanks again for the bump. Fixed this really old issue.

Feel free to bump others. If they're low-hanging fruit, I'll get them out of the way. If not, I'll reclassify with my labels

> When I compare the templatestyle output between xowa and mediawiki there are (at least) two noticeable differences

Thanks. I didn't realize any of this was happening. Just so you know, I did have more work on TemplateStyles on my side.
* If multiple TemplateStyles to the same CSS is on one page, only add it once, not multiple times
* For HTML databases, do not store TemplateStyles CSS in page. Instead, add some sort of MAGIC TOKEN (```<!-- XOWA_TEMPLATE_STYLES:A.css-->```) and instruct XOWA to retrieve from somewhere else.
   * This prevents repetition of a long A.css used across a million pages

With that said:

> 1. mediawiki is compress (any comments and unnecessary space are removed)
If I get the above done, then there is less need for this

> 2. all selectors have an additional class .mw-parser-output
Thanks. Didn't notice that. This will need to be added

> 3. url() entry as the appropriate image needs to be redirected to local storage
Yikes. Yes, this too will need to be added.

> A suggestion is that during the build phase, an extra process be added that goes through the Template namespace and finds and replaces all *.css entries with a compressed, mw-parser-output and url change. (done as a 'user' edit)

I think this can be all done in the TemplateStyles extension. I just need to be able to "cache" that fixed output so that mass parse can re-load the altered .css without having to do the work again.

A sort of major project. Will add it to TODO list.

**Comment by desb42** [comment]
Have just come across a page where the navigation is 'boxed'
![poland](https://user-images.githubusercontent.com/861631/78882778-7826c300-7a50-11ea-8ed2-648917fbfe1d.jpg)

Note the left hand navigation has boxes around it
This page uses `Module:Portal/styles.css`, the first few lines are

    /* {{pp-template}} */
    .portal {
      border: solid #aaa 1px;
      padding: 0; /* Timeless adds padding */
    }
The top level css already has a `.portal` selector
If I edit the Template and add `.mw-parser-output` to each selector then the page returns to its more usual look
![poland2](https://user-images.githubusercontent.com/861631/78882792-81b02b00-7a50-11ea-8911-4ed24a881add.jpg)

**Comment by gnosygnu** [comment]
Thanks for the report! Hope all things are well for you on your side of the world.

I agree that the issue is with `.mw-parser-output`. I think the simplest fix is to add `.mw-parser-output` to each CSS class generated by `<templatestyle>`, which will effectively make the CSS apply to the main content div (where the article is) not any of the portal divs (sidebar; top; etc)

Will do this tomorrow.

Also, as a minor note, MediaWiki actually adds the `templatestyle` CSS directly inline within the article whereas XOWA keeps it at the `<head>`. I chose this route b/c:
* Something strips away inline CSS ( XO-HTML-cleaner / jtidy) so it needed to be put in the `<head>`
* For HTML Databases, it was easier to do `templatestyles` at the `<head>`

**Comment by desb42** [comment]
Personally I'm fine, the lockdown is weird (but hopefully effective)
And I also hope that things are OK for you, over the pond

I cannot remember if I mentioned that I have written a css minify that adds `.mw-parser-output`
In myxowa it is called `Xoh_css_minify_v3.java`
This does not do anything about `url(...)` yet
[Xoh_css_minify_v3.zip](https://github.com/gnosygnu/xowa/files/4460386/Xoh_css_minify_v3.zip)

I have changed a line in Template_styles_nde.java to incorporate it

    html_head.Bld_many(tmp_bfr, css_page_id, Bry_.new_u8(minify.cssmin(String_.new_u8(css_src), 0)) );

**Comment by gnosygnu** [comment]
Cool. Good to hear things are well with you. Germany has been pretty good in terms of fatality rates, but this whole situation has been crazy.

For me, I live near NYC, and though the numbers and overall situation is still grim here, the situation has been recently improving. Personally, I'm doing okay so I'm more than grateful for that.

Regarding the issue, I added the `.mw-parser output` to the templateStyles output in the commit above. Your [Xoh_css_minify class](https://github.com/desb42/myxowa/blob/master/400_xowa/src/gplx/xowa/htmls/Xoh_css_minify_v3.java) is pretty cool, but I wanted to track it in a separate issue: #704 

Thanks again for the solution, as well as tracking it down in the first place! And hope everything stays good for you and yours!
