### ISSUE TITLE
querystring not being escaped

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#465]
I was reviewing a few templates with \<templatedata> and came across this effect on
en.wikipedia.org/wiki/Template:Ship/doc/fixed_prefix:_TemplateData
![doc](https://user-images.githubusercontent.com/861631/57932529-00d5c700-78b3-11e9-91e5-0a746522cb41.gif)
(it has nothing to do with templatedata)

This is an issue identified in Module:Documentation
Within `function p.makeExperimentBlurb` (line 795)
Specifically line 859

    local mirrorUrl = sandboxTitle:fullUrl{action = 'edit', preload = mirrorPreload, summary = mirrorSummary}
In this case `mirrorSummary` has the following content

    Create sandbox version of [[Template:Ship/doc/fixed prefix: TemplateData]]
And goes on to generate the following external link

    [//en.wikipedia.org/wiki/Template:Ship/doc/fixed_prefix:_TemplateData/sandbox?preload=Template:Documentation/mirror&action=edit&summary=Create sandbox version of [[Template:Ship/doc/fixed prefix: TemplateData]] mirror]

The issues is that the querystring is not escaped
In wikipedia the equivalent is

    [//en.wikipedia.org/wiki/Template:Ship/doc/fixed_prefix:_TemplateData/sandbox?preload=Template%3ADocumentation%2Fmirror&action=edit&summary=Create+sandbox+version+of+%5B%5BTemplate%3AShip%2Fdoc%2Ffixed+prefix%3A+TemplateData%5D%5D]] mirror]

The Module calls `:fullUrl` which in turn calls the java function `GetUrl` in Scrib_lib_title.java which in turn calls `Pfunc_urlfunc.UrlString`.
This function just tacks the querystring (unmodified) onto the link

I think that the querystring should be escaped

**Comment by gnosygnu** [comment]
Thanks for the detailed write-up, especially the clear contrast in behaviors between MediaWiki and XOWA.

> The Module calls :fullUrl which in turn calls the java function GetUrl in Scrib_lib_title.java which in turn calls Pfunc_urlfunc.UrlString.

The problem actually turns out to be fairly complicated. The above fix involves url-encoding the query arguments when they are passed as array arguments, which should only happen in Scribunto

Anyway, more detail below. Thanks again!

---

The main issue is MediaWiki's fixUrlQueryArgs: https://github.com/wikimedia/mediawiki/blob/master/includes/Title.php#L1887

It takes a ```$query``` which can be either a string or an array. 
* If it's a string, it does nothing
* If it's an array, it url-encodes them

For the purposes of Pfunc_urlfunc, it always passes a string, so there should be no encoding. For example, the following is not encoded in Wikipedia's Sandbox (https://en.wikipedia.org/w/index.php?title=Wikipedia:Sandbox&action=submit)

```
{{fullurl:Page|a / bb=c / d}}
```

which becomes

```
//en.wikipedia.org/w/index.php?title=Page&a / bb=c / d
```

However, it looks like the Scribunto functions in TitleLib and UriLib do take arrays (such as in your example above)

```
sandboxTitle:fullUrl{action = 'edit', preload = mirrorPreload, summary = mirrorSummary}
```

This will be url-encoded. 

Ideally, the precise fix is to change Pfunc_urlfunc.UrlString so that it does the same string / array bifurcated behavior. However, that's a bit of refactoring, and it also involves relaxing a lot of type-safety rules which is not ideal.

So, for now, I added the array behavior to the XOWA part of Scribunto code. I've confirmed with unit-tests as well as ad-hoc tests against Scribunto's lua console
