### ISSUE TITLE
lua throw seems to fail

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#475]
I was reviewing some errors is the dump of enwikiversity and found this invoke fail

    20190525_070555.564 invoke failed: Web_Science/Part2:_Emerging_Web_Properties/Hearding_Behavior/Summary,_Further_readings,_Homework {{#invoke:Mooc|render|base=Web Science/Part2: Emerging Web Properties}} [err 0] <gplx> =Module:Exception:2 attempt to index ? (a nil value)
        stack traceback:
        Module:Exception:2: in function <Module:Exception:1>
        Module:Mooc:92: in function <Module:Mooc:91>
        mw.lua:531: in function <mw.lua:530>
        [Java]: in function '__index'
        g:/xowa/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:75: in function <g:/xowa/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:74>
        [Java]: in ?: ttl=Web_Science/Part2:_Emerging_Web_Properties/Hearding_Behavior/Summary,_Further_readings,_Homework excerpt={{#invoke:Mooc|render|base=Web Science/Part2: Emerging Web Properties}}
        [trace]:
          gplx.xowa.xtns.scribunto.Scrib_core.Handle_error(Scrib_core.java:219)
          gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.Dispatch_as_kv_ary(Luaj_engine.java:80)
          gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.CallFunction(Luaj_engine.java:59)
          gplx.xowa.xtns.scribunto.Scrib_core.Invoke(Scrib_core.java:185)
          gplx.xowa.xtns.scribunto.Scrib_invoke_func.Func_evaluate(Scrib_invoke_func.java:71)
          gplx.xowa.parsers.tmpls.Xot_invk_tkn_.Eval_func(Xot_invk_tkn_.java:30)
          gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:258)
          gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_tkn(Xot_tmpl_wtr.java:103)
          gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_tkn(Xot_tmpl_wtr.java:35)
          gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_all(Xot_tmpl_wtr.java:23)
          gplx.xowa.parsers.Xop_parser.Expand_tmpl(Xop_parser.java:50)
          gplx.xowa.parsers.Xop_parser.Expand_tmpl(Xop_parser.java:44)
          gplx.xowa.parsers.Xop_parser.Parse_text_to_wdom(Xop_parser.java:102)
          gplx.xowa.parsers.Xow_parser_mgr.Parse(Xow_parser_mgr.java:99)
          gplx.xowa.addons.bldrs.mass_parses.parses.wkrs.Xomp_parse_wkr.Exec(Xomp_parse_wkr.java:138)
          gplx.xowa.addons.bldrs.mass_parses.parses.wkrs.Xomp_parse_wkr.Invk(Xomp_parse_wkr.java:204)
          gplx.Gfo_invk_.Invk_by_msg(Gfo_invk_.java:34)
          gplx.core.threads.Thread_adp.run(Thread_adp.java:33)
          java.lang.Thread.run(Thread.java:748)
The xowa browser view of this is
![versity1](https://user-images.githubusercontent.com/861631/58369453-66990300-7ef2-11e9-9074-db1aa27c1c44.jpg)

The mediawiki version of this page also gives an error
![versity3](https://user-images.githubusercontent.com/861631/58369445-394c5500-7ef2-11e9-9da2-7555c70c6390.jpg)

The mediawiki error message comes from Module:Mooc
Looking at lines 99-103

    local index = IndexParser.parseIndex(self:getIndex(), itemPath, self:getBaseUrl());
    if not index then
        throw('failed to render item @ "' .. itemPath .. '": item not found');
    end
shows the circumstance that generates the error

Using `dbg` I have traced the failure to the throw statement
I am not sure why the error message is not shown

**Comment by gnosygnu** [comment]
As always, thanks for all the detailed points, especially the stack trace. It greatly helped me to narrow down the main cause

Anyway, fixed with the commit above. More details below.

Thanks!

---

As you identified, the main problem is en.wikiversity.org/wiki/Module:Exception. Fortunately, this module was extremely small. I added dbg statements like the following:

```
function throw(errorMessage)
dbg('errorMessage', errorMessage);
dbg('debug', debug);
dbg('debug.traceback', debug.traceback);
dbg('debug.traceback(errorMessage, 2)', debug.traceback(errorMessage, 2));
	error(debug.traceback(errorMessage, 2));
end
```

This rendered the following error in en.wikiversity.org/wiki/Web_Science/Part2:_Emerging_Web_Properties/Hearding_Behavior/Summary,_Further_readings,_Homework?action=edit

```
errorMessage failed to render item @ "Hearding Behavior/Summary, Further readings, Homework": item not found 
debug nil 

Script error: =Module:Exception:4 attempt to index ? (a nil value)
```

So, the ```debug``` function was null. After some head-scratching and investigation, I finally found the culprit: https://github.com/gnosygnu/xowa/blob/5721913241e83d209dfcb261280bd6eec76df3b8/res/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua#L608-L610

I had commented out these lines a long time ago (2013-10) because of some random error when I was first integrating Scribunto into XOWA. As the diagnostics page runs fine with them uncommented (home/wiki/Diagnostics/Scribunto/All), I went ahead and uncommented
