### ISSUE TITLE
accidental character in url request

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#480]
I was reviewing an issue and cut and pasted a link to check if the error still existed and came across a subtle issue

I had intended the link `it.wikipedia.org/wiki/Airbus_Group` but accidentally I copied `it.wikipedia.org/wiki/Airbus_Group]` - note the close square bracket

This caused xowa-server to fail with <java.lang.NullPointerException>
I tracked this down to Xoa_ttl.java
The parser does not like square brackets (and some others) [line 410] and aborts.
This causes the ttl object to be null - which causes all sorts of downstream problems

I do not think aborting is the right thing to do - but not sure what is

**Comment by gnosygnu** [comment]
Thanks for the report. This looks like a simple fix. I'm working on some TemplateStyle issues at the moment, but will hop to this one, or other low-hanging fruit next

**Comment by gnosygnu** [comment]
> I do not think aborting is the right thing to do - but not sure what is

I thought about this for a bit, and decided to navigate to a "Special:XowaError" page. See screenshot below as well as commit above.

Hopefully this is intuitive, but let me know if you have any objections. Otherwise, thanks!

![XowaError](https://user-images.githubusercontent.com/4994104/58767994-d72ec800-8561-11e9-8e2f-e0399617961a.png)
