### ISSUE TITLE
subtle difference for bad &#...;

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#494]
I came across this page
en.wikipedia.org/wiki/Senoue_Nobuyasu

I have subsequently edited this page on Wikipedia

However the wikitext (generated by a bot)

    ?í?‘˜Q–&#x; E•??«•Ò(‚¹)
is interpreted subtly differently between mediawiki and xowa-gui and xowa-http

Mediawiki:
![chars1](https://user-images.githubusercontent.com/861631/59564684-9a72ce80-9041-11e9-84dd-96cc9e27170f.jpg)
xowa-gui:
![chars2](https://user-images.githubusercontent.com/861631/59564687-a363a000-9041-11e9-8e7e-28e835e32a71.jpg)
xowa-http: (Chrome browser)
![chars3](https://user-images.githubusercontent.com/861631/59564690-b70f0680-9041-11e9-8b4d-b69e061d7a7b.jpg)

Its the sequence `&#x;` that is triggering the difference

Mediawiki on finding an invalid sequence leaves it alone
Xowa 'returns' the value `0` which the gui interprets one way and Chrome another

**Comment by gnosygnu** [comment]
Cool. Thanks for the detailed breakdown. If it helps any, you can always skip screenshots and just post page, wikitext, and problem. For example:

* Page: en.wikipedia.org/wiki/Senoue_Nobuyasu
* Wikitext: ```?í?‘˜Q–&#x; E•??«•Ò(‚¹)```
* Problem: &#x; is being interpreted as ```&#0;``` instead of ```&#x;```

But whatever works best for you. Screenshots are always useful, but at this point, I trust 99.5%  of your defects (+/- .5%) and just want to save you some work ;)

Anyway, fixed with commit above. Thanks!
