### ISSUE TITLE
<sytaxhighlight> with highlight but no line

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#498]
the page commons.wikimedia.org/wiki/Template:TemplateBox/doc/example-value
contain the wikitext:

    <syntaxhighlight lang="text" highlight="4-7">
xowa has code to do the necessary highlighting but it requires that the parameter `line=true` to be set also
I have posted a commit to myxowa that addresses this

**Comment by gnosygnu** [comment]
Thanks for the commit: https://github.com/desb42/myxowa/commit/34949abf33fb357faa42204a89ba51610ae0df93.

This looks pretty stratightforward. I'll knock it out tomorrow morning.

**Comment by gnosygnu** [comment]
Forgot to comment last night. Fixed with above commits this morning. 

It looks like 'class="prettyprint lang-text" is related to google-code-prettify which is mentioned in the syntaxhighlight page: https://www.mediawiki.org/wiki/Extension:SyntaxHighlight/en . It's also part of your myxowa branch: https://github.com/desb42/myxowa/search?q=prettyprint&unscoped_q=prettyprint

I assume this works pretty well? If so, I'll create an issue for this and integrate it in near future. I've looked at the Pygments code a while ago, and didn't want to try to transpile / replicate that in Java

Anyway, thanks again for the issue!
