### ISSUE TITLE
Empty log folders

### ISSUE THREAD

**Issue by ZebraFromPluto** [gnosygnu/xowa#510]
Even if you turn off "Logs enabled" in "App - Security", an empty folder is still created in XOWA\user\anonymous\app\tmp\log every time you run the program. Over time this can accumulate into quite a lot of folders.

When this option is turned on, is there any feature in the program to automatically delete old logs, or should you simply go in and delete them yourself whenever you see fit to?

**Comment by gnosygnu** [comment]
Hi, thanks for the detailed report!

This was an oversight in the log creation code. I'll have a fix for this in the same release as #509. This release should happen sometime be end of weekend (or Sunday)

Will comment here again when done. Thanks

**Comment by gnosygnu** [comment]
The above commit deletes all log dirs if logs are disabled. I'd rather not create the log dir in the first place, but this gets complicated. See below.

Also, I like to give credit to users when they report bugs. Right now there's a line in the XOWA change log like this: ```User.Logs: Delete log folders if logs are disabled [#510] {requested by anonymous}```. Let me know if you'd like to be listed as ZebraFromPluto (or something else) or would rather anonymous.

---

This is complicated due to logging happening early, as soon as the app begins.
* XOWA has some logic to capture these logging statements to memory, but it gets flushed before the ```Logs enabled``` setting is loaded
* Changing the above requires a good deal of code change, and I'd rather postpone that until it's necessary.

**Comment by ZebraFromPluto** [comment]
Doing the fix that way should be okay. You can use ZebraFromPluto if like, it's just a virtual name after all. ;)

**Comment by gnosygnu** [comment]
Cited as ZebraFromPluto. See http://xowa.org/home/wiki/Change_log/v4.6.2.1907

Thanks again!
