### ISSUE TITLE
Script error in en.wikipedia.org/wiki/Adıyaman

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#522]
In the above page (dump 2019-06-01) is the following script error

    Script error: @g:/xowa/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:59 vm error: gplx.Err: negative len: bgn=11 end=1 excerpt= Province|Adıyaman]]

The logs indicated that Module:ISO_3166 was involved

After much investigation it seems to come down to the line

    text = mw.ustring.upper(text)
where text causing the issue is `[[Province|Adıyaman]]

I suspect something to do with unicode (that is the `ı` in `Adıyaman`

**Comment by gnosygnu** [comment]
I couldn't reproduce this now. I don't know if it's somehow related to #520 or #504 but I tried with and without the fix for #520 . I don't see anything in my logs (see below) and the page renders fine (no script error) 

Can you try the fix from #520 and see if that fixes the issue? If it doesn't try the following:

* Go to home/wiki/Module:Test
* Replace the page with the following
```
local p={}
function p.string_upper(frame)
   return mw.ustring.upper(frame.args[1])
end
return p
```
* Go to home/wiki/Wikipedia:Sandbox?action=edit
* Preview the following wikitext
```
{{#invoke:Test|string_upper|Adıyaman}}
```

I get ```ADIYAMAN```

Also, as a final random note, the Turkish ```ı``` has weird casing rules. For reference, see http://www.i18nguy.com/unicode/turkish-i18n.html . It's possible that this may be related to the root cause.


---

```
20190726_035444.755 page_load: loaded wikitext; page=Ad?yaman wikitext_len=13984
20190726_035444.810 jtidy.init; elapsed=23
20190726_035444.901 page.async: url=en.wikipedia.org/wiki/Ad?yaman
20190726_035444.901 redlink.redlink_bgn: page=Ad?yaman total_links=170
20190726_035444.901 page.load: url=en.wikipedia.org/wiki/Special:XowaSystemData?type=log_session
```

**Comment by desb42** [comment]
oops, my bad (again)

I was experimenting with different logic for handling upper/lower casing
[rather than a trie, I am using a state machine]
And (guess what), I got the logic wrong

Having corrected that issue, all is well

**Comment by gnosygnu** [comment]
No worries. Thanks for the follow-up!
