### ISSUE TITLE
Import fails because of search for English Wikipedia on 32-bit Windows machines (Major Failure Offline Import Windows 32 in Xowa Version 3.*.*.*)

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#55]
Hi Mr Gnosy.

You might remember in April I reported that I was unsuccessful in importing my 2014 Xowa data base, but had no recent data base from Wiki Dumps to test with. 

At the time I emailed you the session file, but you reported that it did not reveal anything significant that was helpful.

On 1 May I downloaded the most recent English Wiki Dump **2016-04-07** and proceeded to do an **offline** import on my Xowa **Windows 7 32** machine and it failed in the exact same spot as my on 2014 English Wiki data files.

The failure took place about 70 minutes into the import just as the following files was created **xowa.wiki.pagelinks.sqlite3**.
Here is snapshot of what was displayed on the progress bar left bottom of screen.

![xowa-win-7-32-fail](https://cloud.githubusercontent.com/assets/12995082/15002166/ae8c4c40-119e-11e6-95dd-b03e187237cc.gif)

I tried another import on my **Windows XP 32** machine, and it failed in exactly the same place.

I then tried another import on my brothers **Windows 7 64** bit machine, and it worked perfectly!

So I now assume that this problem crept in a few versions back when designing the new wiki database layout in Xowa version 3. 

I also assume your working "**Out The Box**" database found on **archive.org** was most probably created on **Windows 64** bit platform.

I also assume that anyone attempting to do a **online** import on Windows 32 will also fail.

Finally I assume you will recreate the very same problem if you attempt to import and English Wiki database on any **Windows 32** platform, and will thus be easier for you to detect the exact point of failure in your 32 bit Windows version.

Gratefully I found a temporary work around till you solve this recent issue :)

Warm regards.

William

**Comment by gnosygnu** [comment]
Hi! Thanks for opening the issue and documenting it so well.

There is a known issue with building on Windows XP 32-bit. I ran into it, and was unable to fix it. See: http://xowa.org/home/wiki/Blog/2016-04.html#.28Desktop.29_Faster_search_database_build .

I did try on a Windows 7 64-bit processor but 32-bit JRE, and it did work. Unfortunately, I don't have a Windows 7 32-bit processor lying around. For what it's worth, It also worked on a Mac OS X 64-bit machine and a Linux 64-bit machine. 

I believe it's failing due to Xerial's sqlite3 wrapper. The problem is probably somewhere in the 32-bit Windows binary. It fails with an uncatchable error and I can't use a breakpoint on it. Right now, I'm waiting for Xerial to update their build, but if it takes longer, I may try to do it myself.

For now, there isn't much else to be done about it. I'll keep this issue open and will reinvestigate in a few weeks.

Let me know if there's anything else. Thanks again.

**Comment by gnosygnu** [comment]
Just a short update. I looked at this issue, and it's still hard. Basically, something is causing sqlite to fail on Windows 32 bit machines only. Because the failure is happening on the JNI / C level, there's little I can do to debug or ignore at the Java level.

I'm going to try breaking up this search step into smaller steps, but this isn't easy, and will probably take some time.

**Comment by gnosygnu** [comment]
I upgraded XOWA to use the latest version of the SQlite JDBC jar (3.18.0). This version now works on my 32-bit dev box, though I don't know how long (<24 hours).

If anyone needs would like to try the patch out now, let me know, and I"ll upload a beta copy. Otherwise, I'll mark this issue closed after the next release (sometime in the next few weeks)

Thanks.

**Comment by gnosygnu** [comment]
Tonight's release (v4.5.7.1706) includes sqlite-jdbc-3.18.0.jar . As per above, I am going to mark this issue closed for.
