### ISSUE TITLE
category stats not being calculated

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#557]
looking at en.wiktionary.org/wiki/Category:English_conjunctions
Mediawiki has
![cats3](https://user-images.githubusercontent.com/861631/63494100-e95f3900-c4b4-11e9-9e95-da04ec2e4bde.jpg)
The Table of Contents (high lit in red) does not appear in xowa

Investigating, the wikitext points to Template:Poscatboiler
This in turn calls Module:Category_tree
This contains the line:

    inCategory = mw.site.stats.pagesInCategory(titleText, "pages")
which is returning 0 in xowa (hence no TOC)

The issue is that titleText in this case is `English conjunctions` (note the space character)

In 400_xowa\src\gplx\xowa\xtns\scribunto\libs\Scrib_lib_site.java
in the function `PagesInCategory`
the line

    ctg_name = Bry_.Replace(ctg_name, Byte_ascii.Space, Byte_ascii.Underline);
needs to be added just after

    byte[] ctg_name = args.Pull_bry(0);
so as the next steps can find the entry in the page table

**Comment by gnosygnu** [comment]
Cool. Great info. Thanks for tracking that down; I know it isn't easy. I figure it must have taken at least an hour or so on your side.

On my side, I made the change (and added a test). I ended up using ```ctg_name = ctg_ttl.Page_db();``` to handle other possible normalizations.

Let me know if anything else.

Thanks!

**Comment by desb42** [comment]
I did not time myself; however, that seems about right.
I find constructing a lucid issue itself can be quite time consuming
The space/underscore issue has nipped in the past

**Comment by gnosygnu** [comment]
> I did not time myself; however, that seems about right.

Yeah, from my prior experience, 1 hour is the low estimate in terms of finding the root cause. Sounds like you're just as good navigating the XOWA code base as me. ;)

> I find constructing a lucid issue itself can be quite time consuming

Feel free to go light on details. It's amazing enough that you find these issues and track down the cause. Please don't spend time trying to make the issue lucid. If you give me a simple "this is the bug" and "this is my proposed fix" I should be able to figure out the rest. If not, well, I'll ask questions. :)

> The space/underscore issue has nipped in the past

Yeah, I try to be mindful of it when coding, but a few cases slip through. Hopefully it's very few
