### ISSUE TITLE
possible memory leak in defn cache

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#561]
Looking at the code in Xow_defn_cache.java and its supporting class Gfo_cache_mgr.java, I think there may be a memory leak.

When Xow_defn_cache.java uses Add it potentially adds two cache.Add_replace entries (one with a zero size)

When this cache overflows I believe that Gfo_cache_mgr.java sorts the cached entries by size and removes the biggest until the cache size is below some threshold.

If that is the case, then the zero length entries will never get removed, but they will still have reference to the defn objects (hence, I think, a memory leak)

This is more of a thought experiment than proof

**Comment by gnosygnu** [comment]
Yeah, I agree there is a minor bug in that 0-length entries will not get removed. I addressed that with the commit above.

That said, this really shouldn't cause a memory leak. The build script has a default of ```cleanup_interval``` of 50 which should call ```Xow_cache_mgr.Free_mem``` every 50 pages. In turn, ```Free_mem``` will eventually call ```hash.Clear``` which will remove everything from the Xow_defn_cache, including the 0-length entries.

Finally, I think this cache is overly optimizing memory-usage.  I'm really hoping to dump this cache whenever I finish the port of the MediaWiki template parsing. I tried to dump it now, but a lot of template unit tests are hooked up to it and I didn't want to update them since most of this should be going away. If it's still problematic, let me know, and I'll reinvestigate removal

I'm sort of hoping that the memory-leak issue went away based on your last update in #526. If not, will reopen this issue (or #559) and investigate more then.

Let me know if you there's anything else. Thanks!
