### ISSUE TITLE
Strange TOC generation

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#562]
Using the shell script to build from commit 9bc0c2c75d9fc92ef60ccd16639ddd0a7ab91073, I tried to load the page en.wikipedia.org/wiki/Towson_University_buildings_and_structures (from wikitext) and get
![toc_diff](https://user-images.githubusercontent.com/861631/64066481-1b3d7180-cc12-11e9-9a43-6757c49e15b9.jpg)
I believe the red ellipse should have the save text as the blue ellipse

Not sure how that's happening

**Comment by gnosygnu** [comment]
So, this was a weird bug. It's probably been in there for years. The problem was that there was a byte array trim function which sometimes reused the same byte array. 

More details are below. As always, thanks for the detailed report!

---
First, here is the simplest reproduction step
```
__TOC__
==0123456789012345==
==1234567890123456==
```
This would print 1234567890123456 twice.

Here is the problem:
* The TOC calls a function called ```bfr.To_bry_and_clear_and_trim``` for each item which in turn calls ```Bry_.Trim```
* This function has logic that trims whitespace from the front and back of the byte array
  * However, if there is no whitespace, as an optimization, it returns back the same byte array
* Due to how the bfr gets initialized, this bug only surfaces when strings are 16 length

The commit fixes the above by selectively skipping over the optimization. A few other files are changed because a new variable was added to the public
