### ISSUE TITLE
Bry_fmtr.java and the dirty flag

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#575]
I have been implementing my version of the cite references (to make them wiki dependent)
During that work I noticed a lot of use of formatted strings
Delving down to Bry_fmtr.java, I see that there is a 'compilation' stage instigated if the `dirty`flag is set to true
What I could not find in the code is anything that sets this flag to false
Hence these format strings are 'compiled' every time
So I added a line

    dirty = false;
at line 213

Everything seems to still work!
(Although I have not checked, there ought to be a performance gain)

I have yet to see how this works in a full build (although I do not think there should be a problem)

**Comment by gnosygnu** [comment]
Oops. Nice catch. Missed that. :blush:

It turns out that there needs to be a few more lines because the formatter supports some advanced commands (which are probably not used). Otherwise, the one-line change causes a test to fail.

Also, apologies for lack of commits recently. I'm still slogging through #553 and have been busy between work and personal life. I should have a commit for #553 this week and then will handle a few of the other HTML-DB related issues so I can kick off a clean enwiki build.

Anyway, thanks again for the find. It should increase performance (hopefully signficantly!)

Thanks!
