### ISSUE TITLE
mw.hash.lua not implemented

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#589]
with #587 implemented, I started to rebuild dewiki and across
`de.wikipedia.org/wiki/NetBSD`
This in turn makes use of `de.wikipedia.org/wiki/Modul:Wikidata`
Within this module is the function `getReferences`
which internally makes a call to `mw.hash.hashValue('fnv164', formattedRef)`

I found that mw.hash does not exist
Whats more this is the first time I have heard of hash function 'fnv164'

I have attempted a fix
The FNV hash is using a jar file from http://www.getopt.org/

Please see my lua_hash branch

**Comment by gnosygnu** [comment]
First, thanks @desb42! The above [commit](https://github.com/desb42/xowa/commit/7b87845f4cb31af25929fe4e8c042d6b271ef9df) was immensely helpful in understanding what was involved. Also, nice find with the fnv hash library. :+1: 

This change basically covers three parts:
* Add new java libraries for crypto support: bouncycastle, gnu-crypto, getopt, jacksum
* Rewrite the existing XOWA/gplx hash class framework to easily support adding new hash algos
* Add 44 out of the 52 hash algos from the new libs. There are 8 I couldn't find, which I list below

Let me know if there is anything else. Otherwise, I'm going to try kicking off a 2019-10 de.wiki build and see how far I get.

Thanks again!

---

#### Unimplemented algorithms:

```
tiger128,4
tiger160,4
tiger192,4
snefru
snefru256
gost-crypto
crc32
joaat
```

**Comment by desb42** [comment]
Fabulous - I bet that took a bit of work!

**Comment by gnosygnu** [comment]
Yup, took a bit longer than I expected, but hopefully it's future-proof enough. :smile:
