### ISSUE TITLE
Copy paste links from Xowa to another app

### ISSUE THREAD

**Issue by GitterHubber** [gnosygnu/xowa#61]
Would it be possible to copy a link to a page in Xowa and then paste than link into another app and then when I click that link it opens Xowa and displays the linked page.

**Comment by gnosygnu** [comment]
Hmmm.... Not sure I understand. Do you want to register XOWA as the default internet browser? If you do that, then clicking on links in other apps would open XOWA. However this would apply to all internet links, not just wikipedia ones.

If it's desktop, you'll need to do some registry changes. See http://stackoverflow.com/questions/32671277/how-do-i-register-a-custom-application-as-a-web-browser-in-windows-8-1

Also, just so you know, XOWA Android has a feature like this.

Hope this helps

**Comment by GitterHubber** [comment]
Hi there! thanks for the reply!
I'm on a windows desktop.
To explain the issue further if I currently copy a link from Xowa (by right clicking on the link and then selecting copy)and then paste into an external app it appears like "en.wikipedia.org/wiki/Earth" however this is a web link and links to the online Wikipedia I would like this to be an offline link.
So in the future if I open my external app and click on that link it should either:
1. open Xowa and open the page that the link is associated with or if Xowa is already open it could navigate to the tab of the specified page the link points to.
2. Open the default browser (I don't mind this I can configure Xowa as an Http server) and then opening the specified page in it however for this I think the link has to be in the form "xowa://en.wikipedia.org/wiki/Earth".
I hope I could explain the  issue well.
Thanks again for building a great app!

**Comment by gnosygnu** [comment]
Hi! Thanks for the further explanation.

Just to make sure I follow, here is my understanding:
* Copy a link from XOWA. Let's say: en.wikipedia.org/wiki/Earth
* Paste this link into an external app. Let's say you're pasting this into LibreOffice Calc with Ctrl+K.
* Click the link in LibreOffice Calc. Instead of the link opening in the default browser (let's say, Mozilla Firefox), it opens instead in XOWA

If so, then yeah, I don't think there's an easy way for this. Basically, it would have to do the following:
* Take over as default browser on the system as per the link above: http://stackoverflow.com/questions/32671277/how-do-i-register-a-custom-application-as-a-web-browser-in-windows-8-1
* If the link is a wikipedia link, open it in XOWA
* If it's not a wikipedia link (say www.mozilla.org), then open up a browser and launch the link there.

This is quite a lot for that feature, and probably would not work to your satisfaction. For example, most internet links from external apps would have to launch 2 apps: XOWA and then your browser.

Let me know if this doesn't makes sense, or if you have other ideas. Thanks.

**Comment by GitterHubber** [comment]
Hello Again,

Thanks  for the effort and the suggestions..
I will try configuring Xowa as an HTTP server and see where that leads 
me, probably I can then use the browser for copying the links.

Thanks a million!
Au Revoir!

**Comment by gnosygnu** [comment]
Sure. Let me know if you need any thing else. Otherwise, I'll close this ticket in a few days. Thanks!

**Comment by gnosygnu** [comment]
I'm going to go ahead and close this ticket. Let me know if there's anything else and I'll reopen. Thanks.
