### ISSUE TITLE
Pagebanner: Update css class based on 2019-10 enwikivoyage

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#610]
Minor issue to update css classes for Pagebanner

**Comment by desb42** [comment]
This does not seem to work for me

On further rummaging, there seems to be a lot going on with mustache (server side)

One of the thing I spotted was that xowa seems to be using a mustache file
\xowa\bin\any\xowa\xtns\WikidataPageBanner\templates\banner.mustache 

This file has been updated in
github.com/wikimedia/mediawiki-extensions-WikidataPageBanner/templates/banner.mustache

This version adds (amongst other things)

    {{#isPanorama}}wpb-banner-image-panorama {{/isPanorama}}

I have modified 400_xowa\src\gplx\xowa\xtns\pagebanners\Pgbnr_itm.java
and added

    else if	(String_.Eq(key, "isPanorama"))	return Mustache_doc_itm_.Ary__bool(true);	// until something more substantive
to the `Mustache__subs` function
(having copied the newer version of banner.mustache)

I will now check what css modifications (if any are neccessary)

It seems that pagebanner has gone through an extensive change since the xowa version

**Comment by desb42** [comment]
It seems with this latest version of banner.mustache another flag also needs to be set

    else if (String_.Eq(key, "enable-toc")) return Mustache_doc_itm_.Ary__bool(true);	// until something more substantive

**Comment by gnosygnu** [comment]
Oops. I should've caught that on my end. Made changes below and committed above. Thanks!

---
* Sync the banner.mustache template
* Add implementation for isPanorama
* Put in stubs for enableToc and hasPosition
* Don't show HTML TOC when pageBanner shows

**Comment by desb42** [comment]
> Don't show HTML TOC when pageBanner shows

After I applied this patch, I still get the extra TOC
In my version of Pgbnr_func.java the line

    wiki.Html_mgr().Html_wtr().Cfg().Toc__show_(false);
Is added at the end of `Func_evaluate` as its seems too late to perform this in `Add_banner`

**Comment by desb42** [comment]
On further investigation.
Your patch, displays the extra TOC - only once after startup
Second time refresh the extra TOC does not show

With my patch, there is no extra TOC

BUT...

When the extra TOC is displayed the anchor tags work that is, the link '#Understand' goes to the link

    <h2><span class="mw-headline" id="Understand">Understand</span></h2>
 whereas with no extra TOC there is no 'link'

    <h2>Understand</h2>

**Comment by gnosygnu** [comment]
Oops. Thanks for picking that up. I should've caught that on my side. :(

Anyway, fixed with the commit above. Let me know if anything else. Thanks!
