### ISSUE TITLE
Luaj: DIGIT should not include superscript 1 (Module:Historical populations:60 attempt to perform arithmetic __sub on nil and number)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#617]
Building 2019-11-01 enwiki, I came across this issue with the page `en.wikipedia.org/wiki/Vilnius`

This is trying to build a table of info from some historical data

The error is occurring within the function `getpoprow` of `Module:Historical populations`

The first few lines of the data provided by  `en.wikipedia.org/wiki/Vilnius` are

    |1766|60,000
    |1796¹|17,500 
    |1800|25,400
    |1811|56,300
    |1818²|33,600
Note the superscripted 1 and 2 (for 1796 and 1818 respectively)

It is these superscripts that are triggering the issue; however I think there is a more serious issue

The function `getpoprow` contains some regular expressions that seem to me to behave incorrectly.
For example

    local yearnum = formatnumR(mw.ustring.gsub(year or '', '^%s*([%d][%d][%.%d]+).*$', '%1') or '')
 for the first value, that is, year = `1766`, my reading of this regex should be the result `66` xowa gives `1766`
and for the second `1796¹` it should be `96` xowa gives `nil`

removing all the superscripts displays the table

**Comment by gnosygnu** [comment]
Nice find! This was a bug in my misreading of the PHP Regex code. 

Basically, ```%d``` was being applied to other character classes it shouldn't have (including superscripted numbers).  The behavior was more like Java, but obviously, it should be like PHP. I document more in the commit above: https://github.com/gnosygnu/luaj_xowa/blob/c41937514d2612c48a0f1f967e66aaddd3462bab/src/core/org/luaj/vm2/lib/Str_char_class_mgr__unicode.java#L136

Also, a minor explanation regarding the regex above in case you're curious.

Otherwise, fixed with the commits above. Thanks!

---

```
local yearnum = formatnumR(mw.ustring.gsub(year or '', '^%s*([%d][%d][%.%d]+).*$', '%1') or '')

for the first value, that is, year = 1766, my reading of this regex should be the result 66 xowa gives 1766
```

Actually, it should be 1766. Here's how the regex break down for reference

```%s*([%d][%d][%.%d]+).*$```: Basically, get 2+ digits while skipping whitespace and non-digits
* ```^```: Anchor at beginning
* ```%s*```: Skip over 0+ whitespace
* ```(```: Group 1 starts
  * ```[%d]```: Match digit
  * ```[%d]```: Match digit
  * ```[%.%d]+```: Match either decimal or digit 1+ times
* ```)```: Group 1 ends
* ```.*```: Match any character 0+ times
* ```$```: Anchor at end

**Comment by desb42** [comment]
regex can be a brain twister
Now working as expected - great work
