### ISSUE TITLE
two headers on a wikisource page

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#622]
Looking at
 `en.wikisource.org/wiki/Memorial_from_the_ladies_of_Steubenville,_Ohio,_protesting_Indian_removal`

![twoheads](https://user-images.githubusercontent.com/861631/69704663-cb285b00-10eb-11ea-84cf-3e86273e52c1.jpg)
Note that two 'headers' are displayed

In the wikitext is the line

    <pages index="Memorial from the ladies of Steubenville, Ohio, protesting Indian removal.jpg" include=1 header=0 />
Note the attribute `header=0`

I believe that `header` should be treated as a boolean, default 'false',
where `0` in this case means false (not present, that is, any value means true)

I think this can be fixed with a change in 400_xowa\src\gplx\xowa\xtns\proofreadPage\Pp_pages_nde.java

**Comment by gnosygnu** [comment]
Nice breakdown! Fixed with the commit above. Minor notes below. Thanks!

---

The main problem is that [MW Pages code](https://github.com/wikimedia/mediawiki-extensions-ProofreadPage/blob/master/includes/Parser/PagesTagParser.php#L258) checks if ```header``` is true. Since ```header``` was ```0``` that means it is false.

Added some extra code to try to model the bool rules from https://www.php.net/manual/en/language.types.boolean.php#language.types.boolean.casting
