### ISSUE TITLE
Xtn.Page: Do not escape XML in header previous / current / next links (html showing through)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#624]
looking at `fr.wikisource.org/wiki/La_Petite_Dorrit/Tome_1/Préface`
![spaner](https://user-images.githubusercontent.com/861631/69881426-ef8b5f80-12c4-11ea-85e1-026ba491dcad.jpg)
Some html is peeping through

It seems to be something Lua related (but I could easily be wrong)

**Comment by desb42** [comment]
I think this is a further example
`fr.wikisource.org/wiki/Livre:Dickens_-_La_Petite_Dorrit_-_Tome_1.djvu`
![spaner2](https://user-images.githubusercontent.com/861631/69898219-f316f900-134d-11ea-9fc9-1e4e950dc0f4.jpg)

Ultimately to do with Module:Header template

**Comment by gnosygnu** [comment]
Good catch! I usually miss these sort of details.

The issue was related to some proofreadPages code specific to previous / next links in the header. It was using a general ```Write_to_html``` function which didn't handle ```Caption``` tokens. 

The DEFAULTSORT issue is different, so I split it out to this issue: #625. Will look at it in the next day or so.

Thanks!
