### ISSUE TITLE
Xtn.Is_in: Escape double-quotes as &quot; (encoding discrepancy)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#627]
as a followup to #626 and the comments about the Xoa_ttl class functions
There seems to be an inconsistency

Internally, this class makes use of a two encoders - href_encoder and url_encoder
As far as I can tell the main difference is in the treatment of double quotes

the functions using href_encoder are
Page_url_w_anch
Full_url

and those using url_encoder are
Page_url
Leaf_url
Base_url
Talk_url
Subj_url

This issue came to light while I was examining the behaviour of the links (hrefs) and title text of the page `en.wikisource.org/wiki/A_Critical_Examination_of_Dr_G._Birkbeck_Hills_"Johnsonian"_Editions/The_Preface_and_Dedication`

I think that there needs to be some more functions of the form `XXX_href` to indicate href encoding and the functions of the form `XXX_url` should all use the url encoding

There is a further issue with regard to the `title` attribute within an anchor \<a>, double quotes should be converted to `&quot;` - but I do not know which of the encoders performs this

**Comment by gnosygnu** [comment]
Hey, great write-up as always.

> There is a further issue with regard to the title attribute within an anchor <a>, double quotes should be converted to &quot; - but I do not know which of the encoders performs this

Yeah, there isn't an encoder on Xoa_ttl. It requires a separate call to an "escaper": ```Xoh_html_wtr_escaper.Escape(wiki.Appe().Parser_amp_mgr(), tmp_bfr, subpage_ttl_bry)``` . I really should unify the names (everything should be an encoder / decoder).

At any rate, I fixed this issue in [the first commit](https://github.com/gnosygnu/xowa/commit/b2a6f7bbf168436eb5348db64bee74c435ecd697) by escaping the ```"``` as ```&quot;``` for the ```title``` attribute in the subpages area.

> I think that there needs to be some more functions of the form XXX_href to indicate href encoding and the functions of the form XXX_url should all use the url encoding

This was poor choice of naming on my side. ```XXX_url``` should have been named ```XXX_href```. Both are meant to do encoding for the ```href``` attribute on the ```<a>``` tag (where special characters are ```%``` encoded; EX: ```"``` as ```%22```). I used the term "url" b/c I was using these encoders initially for the url-bar

In addition, there are two encoders in Xoa_ttl: ```href_encoder``` and ```url_encoder```. I forget why I added the 2nd, but it may be during some sweeping refactoring of the 1st.

At present, I don't plan on adding ```_entity_ref``` type utility methods to Xoa_ttl (encode ```"``` as ```&quot;```) b/c the current design is already a bit unwieldy, and these entity_ref methods don't get used enough to justify helper methods. In addition, Xoa_ttl should get normalized to be more like the MediaWiki Title object

At any rate, I made the following changes in [the 2nd commit](https://github.com/gnosygnu/xowa/commit/89d0ba1271390f94278bd7ba54a340a7a4ec95e8):
* Remove the ```url_encoder``` and change all existing usages to ```href_encoder```
* Rename ```href_encoder``` to ```url_encoder``` (because all methods are ```_url```)
* Change ```Full_db_href``` to ```Full_db_url```

One day, I may change all ```_url``` to ```_href``` to better indicate function, but I think that will be quite a ways in the future. In the meantime, I'll stick to the ```_url``` convention for now.

Thanks!
