### ISSUE TITLE
ParserFunctions.Time: Support meridian / timezone (am/pm processing in time values)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#648]
As a consequence of changes I made for #645, when rebuilding enwikivoyage, I get some date format errors - of the form

    20200101_171347.069 date parse err: ttl=Edinburgh/Old_Town txt=9:30AM
    20200101_171347.076 date parse err: ttl=Edinburgh/Old_Town txt=6PM
So I set about implementing this
Please see my latest commit in myxowa 4b7bc4279b4b7a77e110ffcb6099bd06246b5414
for a possible solution

**Comment by gnosygnu** [comment]
Just linking the commit for reference later: https://github.com/desb42/myxowa/commit/4b7bc4279b4b7a77e110ffcb6099bd06246b5414

**Comment by gnosygnu** [comment]
Hey, finally got around to integrating this today. Thanks as always for the thorough job. The XOWA time parser is pretty hand-coded, and it's impressive you were able to get it to work :+1:.

I reworked some of the code, particularly since I'm not so fond of switch-case fall-thru, and also to reduce it. I added a bunch of tests and followed the same direction as your commit, so hopefully everything is covered well.

Also, commit link was super-helpful.

Let me know if anything else. Thanks again!
