### ISSUE TITLE
Images won't appears when using HTTP server

### ISSUE THREAD

**Issue by ve3lst** [gnosygnu/xowa#68]
Hi,

When I run web server on windows using:  `java -jar xowa_windows.jar --app_mode http_server --http_server_port 8080`
The text appears perfectly, but no images. I'd downloaded the images from the links you provided to me 2 weeks ago in #62 . The images appears when using XOWA app.

I noticed when I open a certain enwiki page using XOWA app the images appears in web browser but if I'm opninng a page haven't opened it yet using XOWA images won't appear. Also when I delete "file" folder the images won't appear in the web browser.

BTW, I'm using XOWA 32bit

How I can make images appears in web browser?

Thanks

**Comment by gnosygnu** [comment]
Hi! Sorry about that, but I confirm this is a bug. It looks like I broke image retrieval for Wikitext databases, but not for HTML databases.

Let me fix this for tonight's release. I'll post more details later, but if you want more info, let me know.

Thanks!

**Comment by ve3lst** [comment]
Hi,

Thank you for explaining it for me, good luck fixing it.

Thanks

**Comment by gnosygnu** [comment]
Tonight's release fixes the issue. See https://github.com/gnosygnu/xowa/releases/tag/v3.7.2.1

I provide more detail below if you're interested. Let me know if there are any issues on your side and I'll investigate. Otherwise, I'll close out the ticket in a week's time.

Thanks again for reporting the issue.

----

v3.6.4.* cleaned up the image downloading code. In the process, I accidentally broke image downloading for the HTTP server and Wikitext databases. I didn't catch it because I only tested downloading for the HTTP server and HTML databases. 

Now as for the difference between a "Wikitext" database and an "HTML" database.

#### Wikitext databases ####
* Generated in XOWA at Import Online / Import Offline
* Available since v0.0.0.1 of XOWA
* Slower: Has  Wikitext which must be compiled into HTML
* Does not work on XOWA Android

#### HTML databases ####
* Generated in XOWA by using command line scripts
* Downloaded through Download Central
* Available since v3.6.3.1 of XOWA
* Faster: Only has HTML which doesn't need further parsing
* Works on XOWA Android
* Still missing a few features (for example, doesn't do Categories, Popups)

Since I'm using XOWA Android a lot, I'm doing a lot of my testing with the HTML databases. I just need to get into more of a habit of testing both, which should hopefully improve with time.

**Comment by ve3lst** [comment]
Hi,

Thank you very much for fixing it, It's working perfectly with me now.

I just have one question about "file" folder, do I've to delete it manually after a while or XOWA will do it for me?

That's all. 

Thanks!

**Comment by gnosygnu** [comment]
Great. Thanks for the confirmation!

The short answer is: don't worry about the "file" folder. XOWA will manage it for you.

The longer answer follows.

XOWA uses the file folder as a temporary cache for images. This is because the images need to be saved somewhere on disk so the HTML can show them (just like any other internet browser)

Whenever you view a page, XOWA takes the image (from either the internet or the XOWA image databases) and places a copy in the /xowa/file/ folder. After the cache reaches about 100 MB of space, XOWA will delete old files to bring it back down to 75 MB.

You can control these settings at home/wiki/Options/Files . There's also a button to wipe the cache entirely.

Hope this helps.

**Comment by ve3lst** [comment]
Hi,

Thank you very much for the explanation.

Thanks

**Comment by gnosygnu** [comment]
No problem! I'm going to mark this issue closed then. Thanks!
