### ISSUE TITLE
lua number processing seems imprecise

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#697]
Trying to track down a different error, I came across this one
Looking at `en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population`
(this page has changed over time but the problem occurs with the various version of enwiki I have)
This
![percent1](https://user-images.githubusercontent.com/861631/77245720-9307d380-6c18-11ea-8052-4439e2f9812b.jpg)
shows a percentage figure with lots of zeros

I have found that the responsible code is Module:Percent and that a simple piece of wikitext can trigger this zero response

    {{percentage|1=7538000|2=7773352000|3=|pad=|sigfig=3|%=%|nonscinote=y}}
In xowa-gui, I have added some `dbg` lines to the process to see what is happening

![percent2](https://user-images.githubusercontent.com/861631/77245823-791ac080-6c19-11ea-9c6f-bc650e9a0f6c.jpg)
Then I did a show preview on a few lines of wikitext
![percent3](https://user-images.githubusercontent.com/861631/77245879-0d852300-6c1a-11ea-9bd1-1b9a5ef95331.jpg)
In the top blue box are the values, then a division of the first and second value and the third line shows the percentage (shown as zero in both cases)
The second blue box (from the top of the page) shows the result, and the third blue box is the original wikitext

Similarly for the green boxes

There are (at least) three issues here
1) 7538000 / 7773352000 != 0 (its either 0.0009697232287 or 9.697232287e-04)
2) 56225 / 7776747000 does equal 7.2298867379895e-06 but not `7.2298867379895e-e-06` there is an extra `e-` in there
3) although the value of `pct` is displayed as `0`, the check in the lua code for `if pct ~= 0 then` is returning true - this leads to why there are so many zeros in the result

most confusing

**Comment by desb42** [comment]
Finally bit the bullet and integrated the luaj_xowa sources into my project

I think I have found the issue in `src\core\org\luaj\vm2\LuaDouble.java`

The processing of double to float is trying to trim trailing zeros
But does not do it correctly under some circumstance
Not sure how this has not been found before

This is my suggestion
[LuaDouble.zip](https://github.com/gnosygnu/xowa/files/4374138/LuaDouble.zip)

**Comment by desb42** [comment]
After this fix, there is one subtle difference between my version and mediawiki (at least) for the page `en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population`

mediawiki:
![exponent2](https://user-images.githubusercontent.com/861631/77406120-1279dc00-6dac-11ea-8a17-5f32f34ed79c.jpg)
myxowa:
![exponent1](https://user-images.githubusercontent.com/861631/77406149-1c034400-6dac-11ea-937b-22e19d02710a.jpg)
Note the engineering format
Not sure why that is happening

**Comment by gnosygnu** [comment]
> Finally bit the bullet and integrated the luaj_xowa sources into my project

> I think I have found the issue in src\core\org\luaj\vm2\LuaDouble.java

Thanks a whole bunch for tracking this down . Your one-line code change does fix a bad bug (`0.001` -> `0`).

> After this fix, there is one subtle difference between my version and mediawiki (at least) for the page en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population

Yeah, this has to do with a whole bunch of factors, primarily `Scrib_proc_args` calling `Xstr_str_or_null` which will stringify the double with `Float.toString` instead of calling the `printf` that's in LuaDouble

I have a dirty fix on my side now. Will commit tomorrow.

**Comment by gnosygnu** [comment]
Fixed with the commits above. XOWA now shows the percentages just like MW. Changes listed below. 

@desb42 : Thanks as always for figuring out the main problem, especially since these are so hard to track down. And again, sorry for missing this issue earlier. Feel free to bump any other issues I've missed, and I'll definitely review.

Thanks again!

---

* Fixed trimming logic to not trim numbers like `1.0001` -> to `1` as per desb42@'s commit
* Moved logic down to core double-stringifying logic. Note that `Scrib_proc_args.Xstr_str_or_null` needs to also call the zero-trimming stringifying logic (this was responsible for the sole `4.60x10-4` in the Saint Martin entry above
* Trimmed zeroes from exponent and uppercased the e. For example: `1.1e-05` -> `1.1E-5`. Note that this is necessary once the logic was moved. Otherwise, the bottom rows of the table show up in scientific notation

**Comment by desb42** [comment]
One small issue,

I cannot build using xowa_get_and_make.sh
I get

    [javac] k:\xowa_dev\src\100_core\src\gplx\Double_.java:48: error: package gplx.objects.primitives does not exist
    [javac]                     : gplx.objects.primitives.Double_.ToStrByPrintF(v);

**Comment by gnosygnu** [comment]
Oops. Didn't realize that `xowa_compile.xml` didn't include baselib. Fixed it now and reran on my side. Thanks!
