### ISSUE TITLE
Edit: Save HTML when editing pages (page modification should remove html_db_id)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#699]
Having done a full build of enwiki, I came across an error in one of the pages (`Underground_Atlanta`)
I am running with `Prefer HTML Databases for Read tab` on

As a temporary fix, I decided to change some wikitext in that page.
when I saved this page, the page redisplayed was the original html version - I had to switch `Prefer HTML Databases for Read tab` off to display the corrected version of the page. And then all of the other pages now are unable to use the html version

I suggest that, when a page is saved, its page_html_db_id is reset to -1 to force a wikitext build even when `Prefer HTML Databases for Read tab` is on

**Comment by gnosygnu** [comment]
This started off as a minor 3 or 4 line change, but ended up being more. Decided to have the "Save" action to save the compiled html to a separate `html.user.xowa` database. Had to make other changes due to some broken issues (listed below)

Thanks for the suggestion and sorry for taking so long to resolve!

---

* Saving HTML causes primary key error b/c htmlDbId keeps getting reset to -1
  * Added code to reload htmlDbId before saving. Should probably remove code to reset htmlDbId to -1, but that would require more changes.
* Saving HTML goes to last generated HTML database. In this case, a namespace 0 save went to a namespace 8 database
  * Redirected Edit saves to an `html.user.xowa` database
* Generating HXTN again causes primary key conflicts b/c HXTN only INSERTs
  * Added `Exists` functions
