### ISSUE TITLE
Wiki: 2020-06 German / English Wikipedia

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#738]
Recent versions were originally requested in #717.

I'm still working through some of the more recent bugs, but am going to try for June for a German build. If I run into issues, this will push into July.

**Comment by Ope30** [comment]
Cool that you have 2020-06 in sight! If it doesn't work out this month, then whatever. No problem. Take your time. It can't always work the way we want it to. I am still so grateful that you and desb42 solved the Lua problem!

Keep me informed here if possible. I will check this as often as possible.

**Comment by gnosygnu** [comment]
Just an update. I'm currently blocked by #737, but should have a workaround in the next few days. Will start building 2020-06 DE after that

**Comment by gnosygnu** [comment]
Sorry for the late turn-around.

* Uploaded 2020-06 dewiki to archive.org. See https://archive.org/download/Xowa_dewiki_latest
* Will start working on 2020-06 enwiki next. Hopefully in about 2 or so weeks (a lot depends on how many pages are affected by #737)

**Comment by Ope30** [comment]
Very cool! Thank you very much gnosy for publishing DE 2020-06 Wikipedia!



Now I just have to get a new internet cable in order to download, because I don't have one at the moment (typing this with my phone).


Is it okay if I wait until EN 2020-06 comes out and then download both on the same day? But take all the time you need.                It doesn't have to happen this month if you don't have the time.

**Comment by gnosygnu** [comment]
Hey. Unfortunately, 2020-06 enwiki is blocked due to #771 and #772. I'm going to work on both issues but it looks like the next build won't be until 2020-08. Sorry about that

**Comment by Ope30** [comment]
> Hey. Unfortunately, 2020-06 enwiki is blocked due to #771 and #772. I'm going to work on both issues but it looks like the next build won't be until 2020-08. Sorry about that

No problem 👍

**Comment by gnosygnu** [comment]
Finally uploaded 2020-08 English Wikipedia this week: https://archive.org/details/Xowa_enwiki_2020-08

Was about to make a new release, but ran across a new critical bug

**Comment by ope30new** [comment]
Hey gnosy, it's me, Ope30. This is my new account. I couldn't do anything with my older account (including posting) because I had to verify my email address. I really have no idea what's going on with my email address, it's completely empty. There is nothing in it. I do not receive any E-Mails. I hope I can get it fixed soon. There is no way to get back to my original account as of right now.

Sorry for the late reply man. I have already ordered 2 internet cables. None of them had high speed internet (400MBs was what I had last time). I will order one with maximum capacity. By the way, thank you very much for the work on these two builds and for the publication!

**Comment by gnosygnu** [comment]
Hey, glad to have you back! Let me know how the new builds look. Just so you know, I'm working on a fix by desb42@ which should handle the broken sidebar / topbar.

**Comment by ope30new** [comment]
> Hey, glad to have you back! Let me know how the new builds look. Just so you know, I'm working on a fix by desb42@ which should handle the broken sidebar / topbar.

Okay. Cool 👍

Internet cable will arrive tomorrow. If everything works as it should, DE Wikipedia should be done tomorrow, maybe even EN Wikipedia. 

Man, I am really looking forward to these two builds. It's been a while since I last downloaded a build. I've always loved it when I was done downloading and extracting the wikis putting them into the wiki folder and then launching XOWA knowing that you are up to date having more/updated stuff to read!

**Comment by ope30new** [comment]
I had to rebuild full text search for DE Wikipedia because it didn't work, honestly, no idea why, but it was a fast process. The EN build did not contain full text search (?), so I had to build one too, but that was a fast process too. Both work well. So far no major problems in either. Only a few errors in EN in two specific articles, see en.wikipedia.org/wiki/Oberwesel showing "Audio file "De-Oberwesel.ogg" not found and en.wikipedia.org/wiki/List_of_Wikipedias) with many expression errors and some other type of errors.


 I have tried the latest version (6.4.2009) of XOWA. Looks like you changed the UI a little bit, cool! The only problem I had with the latest version so far is that the whole text "This page was last edited" is too big. Maybe there is something I can do to fix this. I will try.

**Comment by gnosygnu** [comment]
Cool, I didn't think full-text works b/c of JDK 8. Also, XOWA's English Wikipedia's full-text search is broken due to the nature of the build (it takes almost 10 days). I'll remember to do another full-text build only after the main build completes.

> en.wikipedia.org/wiki/Oberwesel showing "Audio file "De-Oberwesel.ogg" not found and en.wikipedia.org/wiki/List_of_Wikipedias) with many expression errors and some other type of errors.

Hmm, I checked both pages and don't see any errors. Are you still using `lua` here? home/wiki/Special:XowaCfg?grp=xowa.addon.scribunto . If so, please change to `luaj`.

> I have tried the latest version (6.4.2009) of XOWA. Looks like you changed the UI a little bit, cool! The only problem I had with the latest version so far is that the whole text "This page was last edited" is too big. 

Unfortunately, all the changes are unintentional. Wikimedia changed the skins recently and a lot of UI elements are showing incorrectly.  For example, the top-bar and the side-bar. For more info, see #797

I don't see `This page was last edited` as having changed. Can you post a screenshot when you get a chance? Thanks!

**Comment by desb42** [comment]
To add my pennies, sometime in the last 6 months, mediawiki has changed the font size of the `This page was last edited` (I cannot remember if they made it smaller or bigger)

A way to ensure that the latest CSS is being used is to delete the directory tree 
XOWA_ROOT\user\anonymous\wiki\en.wikipedia.org
Basically all the subdirectories of XOWA_ROOT\user\anonymous\wiki\ can be deleted EXCEPT `home`

This does require a restart of xowa

**Comment by gnosygnu** [comment]
@desb42 : Yup that works.

Sorry for being offline for the past week or two. I've had some personal affairs to tend to, and work has been (and still is) pretty brutal.
