### ISSUE TITLE
mw.ext.data.get can take two arguments

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#779]
This function, used to access commons Data: entries, has a formal parameter list of (title, language) in 
bin\any\xowa\xtns\JsonConfig\JCLuaLibrary.lua

As far as I can tell all calls in enwikibooks use a single argument - language is `nil`
eg en.wikibooks.org/wiki/Java_Programming/Methods
I have found an instance in dewiki that uses the language parameter (and sets it to `_`)
eg de.wikipedia.org/wiki/Wikipedia:Lua/Modul/WikidataScheme/Gadget

The code in 400_xowa\src\gplx\xowa\xtns\jsonConfigs\scribunto\Jscfg_scrib_lib.java does not check for a second parameter

Reviewing the php code at
https://github.com/wikimedia/mediawiki-extensions-JsonConfig/includes/JCLuaLibrary.php
I read this as Localizing the data except if the second parameter is `_`

To that effect, I have changed the java file
[Jscfg_scrib_lib.zip](https://github.com/gnosygnu/xowa/files/4986769/Jscfg_scrib_lib.zip)

**Comment by gnosygnu** [comment]
Cool. Thanks for the breakdown. Looks straightforward enough. Will slot it for this week. Thanks!

**Comment by gnosygnu** [comment]
Fixed with the commit above. As always @desb42, the code was extremely useful, as I didn't quite understand what was going on in the MW version. Did change approach slightly to model https://github.com/wikimedia/mediawiki-extensions-JsonConfig/blob/master/includes/JCLuaLibrary.php#L41-L48 . Also added some tests.

Thanks again!
