### ISSUE TITLE
Latest XOWA and old images file (also, update Czech wikis)

### ISSUE THREAD

**Issue by MacSquirrel-Jedi** [gnosygnu/xowa#78]
Hello,  i'm using cs.wikis but they are now more than 1 year old. So i bulid new (latest Xowa app) updated (category 2) from Wikimedia dumps "-20160801-" but there is no images for offline use. So i cut the images file from Xowa_csbundle_2015-04-23.7z and paste them to updated wikis. It's working for all cs.wikis instead of cs.wikipedia.org this does not work this way. So maybe it could be good, paste in future published bundle last working XOWA app. Best regards, Mac

**Comment by gnosygnu** [comment]
Hi! Thanks for the details.

Your approach is correct. Nice job figuring it out on your own.

Unfortunately, it doesn't work due to some changes between 2015-04 and today. As a result, it's using "cs.wikipedia.org-file.xowa" (2016-08) instead of "cs.wikipedia.org-file-core.xowa" (2015-04)

To get it to work, try any of these three options:
* Update your config with SQLite. This is the quickest but needs developer know-how 
    * Open cs.wikipedia.org-core.xowa with a sqlite shell
    * Run the following SQL: UPDATE xowa_cfg SET cfg_val = 'lot' WHERE cfg_key = 'layout_file';
    * Start XOWA
* Download my copy from my google drive
    * I ran the above SQL, zipped it, and uploaded it my google drive. You can just replace your "cs.wikipedia.org-core.xowa" with my version: https://drive.google.com/open?id=0B9cb52zjL2rIUV9OYzhOSFFKOW8
* Change XOWA to default wikis with an XML dump size to 500 MB. This is a global setting, so it will affect all new imported wikis, not just cs.wikipedia.org
    * Go to home/wiki/Options/Config_script
    * Enter in "xowa.api.bldr.wiki.import.layout_file_max = 500;"
    * Save
    * Reimport cs.wikipedia.org. When it's done, you'll see a "cs.wikipedia.org-file-core.xowa", not "cs.wikipedia.org-file.xowa"
    * Copy over the 2015-04 file databases

Finally, I'll update the cs.wikipedia images later this month. I'm still working on en.wikipedia for this week, and will be doing de.wikipedia.org next week. I'll try to get cs.wikipedia done for next week also, but that may spill over into the following week.

Thanks.

**Comment by gnosygnu** [comment]
One other note. Unfortunately, image updates need to be maintained and I'm the only one generating them. I fell behind due to XOWA Android, and am trying to catch up. I also ended up rewriting a good deal of the dump process over the past month to handle a multi-threaded architecture (for speed purposes)

I'm going to march through the wikis again, and then try to set up some sort of automated system for it. Unfortunately, this automated system will probably take some time. In the meanwhile, the manual process still requires some baby-sitting. Not much, but it can vary from an hour to many (the latter if there's some parser bug)

If anyone's interested in going thru this, I'd be more than happy to help with any questions / setup. There's more info on the process here: http://xowa.org/home/wiki/Dev/Command-line/Thumbs .

Thanks!

**Comment by MacSquirrel-Jedi** [comment]
Hi, thx for reply. Sorry but i can't get it work by any of these steps above or their combinations... it will be better for me, just wait for update :) 

I'm constantly viewing your web and know, how often you are updating your app. It's realy impressing! have good luck with multi-threaded.I can help you generate images if you want, but i'm just a user. I can do only elementary steps :)

**Comment by gnosygnu** [comment]
> Sorry but i can't get it work by any of these steps above or their combinations... 

Hmm... I tried again and it looks like I messed up the Google Drive option. Sorry about that.

Meanwhile, it looks like the other two options aren't even necessary. I just tried unzipping them now, and it did pick them up. I'll have to debug more, but I'm in the middle of something.

If you're curious, these were my steps:
* Using XOWA v3.8.3
* Went to home/wiki/Dashboard/Import/Online
* Clicked on "download" next to cs.wikipedia.org
* Waited for the download
* Downloaded and unzipped the files from https://archive.org/download/Xowa_cswiki_latest/Xowa_csbundle_2015-04-23.7z
* Placed them in C:\xowa\wiki\cs.wikipedia.org. These were the files I had.
```
cs.wikipedia.org-core.xowa
cs.wikipedia.org-file-core.xowa
cs.wikipedia.org-file-ns.000-db.001.xowa
cs.wikipedia.org-file-ns.000-db.002.xowa
cs.wikipedia.org-file-ns.004-db.001.xowa
cs.wikipedia.org-file-ns.014-db.001.xowa
cs.wikipedia.org-file-ns.100-db.001.xowa
cs.wikipedia.org-file-user.xowa
cs.wikipedia.org-text.xowa
```
* Visited cs.wikipedia.org/wiki/Země . I clicked around on other pages, and images loaded there also, though many are missing.

> it will be better for me, just wait for update :) 

Yup. Czech wikis will be up after German.

> I'm constantly viewing your web and know, how often you are updating your app. It's realy impressing! 

Cool. Thanks for the encouragement!

> .I can help you generate images if you want, but i'm just a user. I can do only elementary steps :) 

Thanks for the offer. I'll try to streamline it more in the coming months. Any new info will be at http://xowa.org/home/wiki/Dev/Command-line/Thumbs . Feel free to ask if you have any questions.

**Comment by gnosygnu** [comment]
I uploaded the Czech wikis today. To get them, do the following:

* Go to home/wiki/Special:XowaDownloadCentral
* Click the "Download" icon to the right of the "Available" table
* The Czech wikis will appear at the bottom of the "Available" table.

Let me know if there's anything else. Otherwise, I'll close out the issue in a few days.

Thanks!

**Comment by MacSquirrel-Jedi** [comment]
It's working nice .)

thx

**Comment by gnosygnu** [comment]
Great! Good to hear! Thanks!
