### ISSUE TITLE
Imported/Expanded on Linux, now want to use on Mac

### ISSUE THREAD

**Issue by sykaleo** [gnosygnu/xowa#79]
I have a full build of Linux 64 xowa with English wiki and Images.  Saved it on my hard drive and it works on all my linux machines.  Now I want to be able to run a Mac 64 build of xowa, but to use the same 130GB+ english wiki that I downloaded on the linux.  Due to data caps and I can't run the whole download again.  Is there a way to get my Mac Xowa to just read the wiki source files from the Linux folder?

Or what should I do?

![mac-wiki](https://cloud.githubusercontent.com/assets/1558276/17836976/58c55556-67e1-11e6-9d73-8d8dc0e68412.png)

**Comment by gnosygnu** [comment]
Hi! There are two things you can try:

## Run it from the same folder
Let's say your drive is an external drive (or flash card). Just unzip all the packages to the same folder.

For example, let's use Windows and Mac OS X
* Attach your external drive to your Windows computer. Let's say it shows up as the "X" drive
* Unzip the xowa_app_windows_64 package to X:\xowa. You'll have a file called "X:\xowa\xowa_windows_64.jar" and many others
* Unzip the xowa_app_macosx_64 package to X:\xowa. You'll have a file called "X:\xowa\xowa_macosx_64.jar" and many others
* Copy all your wikis to "X:\xowa\wiki\". You'll end up with files like "X:\xowa\wiki\en.wikipedia.org\en.wikipedia.org-core.xowa" and many others
* Double-click "X:\xowa\xowa_64.exe". This will launch XOWA and read English Wikipedia from your X drive
* Detach the drive and attach it to the Mac OS X machine. It should show up as "your_drive"
* Launch Terminal and run something like "sh /Volumes/your_drive/xowa/xowa_macosx_64". This will launch XOWA and read English Wikipedia from "your_drive"

This is the recommended way. I do this when I carry around my SD card from one machine to another.

## Run it from different folders
This only makes sense if you're trying to do a server-client model. Or, the files are (a) on an internal drive and (b) you are sharing that drive across multiple machines. Otherwise, the other option is much easier

For example, let's use a Windows machine (server) and a Mac OS X (client)
* Unzip the xowa_app_windows to your Windows C drive. You'll have a file called "C:\xowa\xowa_windows_64.jar" and many others
* Copy all your wikis to "C:\xowa\wiki\". You'll end up with files like "C:\xowa\wiki\en.wikipedia.org\en.wikipedia.org-core.xowa" and many others
* Double-click "C:\xowa\xowa_64.exe". This will launch XOWA and read English Wikipedia from your C drive
* Now, unzip the xowa_app_macosx_64 package to your Mac OS X machine. You'll have a file called "/Users/your_user_name/xowa/xowa_macosx_64.jar" and many others
* Launch Terminal and run something like "java -Xmx256m -d64 -XstartOnFirstThread -jar /Users/your_user_name/xowa/xowa_macosx_64.jar --wiki_dir //YOUR_WINDOWS_SHARE/C/xowa/wiki/
    * This will launch XOWA on your Mac, but tell it use the wikis from your Windows machine

Hope this helps!

**Comment by sykaleo** [comment]
The above works perfectly for Linux to Mac!  

I had already extracted them all out, but what I did was move the .sh and .jar from Mac and the .exe and .jar from Win to the linux xowa folder.  I also copied over the mac_64 and win_64 folders from the bin/ directory to the linux bin directory too.  

Haven't tested it on Windows, but the full English wiki is working on Mac from the original Linux build and wiki download.

Thanks again

![xowa_multi](https://cloud.githubusercontent.com/assets/1558276/17844531/76c3e4ac-6875-11e6-816c-f80a768a076c.png)

**Comment by gnosygnu** [comment]
> I had already extracted them all out, but what I did was move the .sh and .jar from Mac and the .exe and .jar from Win to the linux xowa folder. I also copied over the mac_64 and win_64 folders from the bin/ directory to the linux bin directory too. 

Yup! That works also. Basically, you don't have to worry about files from different Operating Systems conflicting with each other.

> Haven't tested it on Windows, but the full English wiki is working on Mac from the original Linux build and wiki download.

You shouldn't have any problems with Windows. That's actually my main system. :)

Let me know if there's anything else. Otherwise I'll close this issue out by next week.

Thanks!

**Comment by gnosygnu** [comment]
I'm marking the issue closed for now. Let me know if there's anything else. Thanks.
