### ISSUE TITLE
multithread false positives

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#818]
I have been rebuilding itwiki (2020-09-01) and was getting many #invoke errors that I cannot reproduce if I look at the page in xowa-http or xowa-gui

They all took the form

    {{#invoke:Controllo Wikidata|main}} [err 0] <gplx> bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:59 vm error: gplx.Err: null

I decided to try running this build through a debug session - which itself changes the timings

I have discovered that these issues emanate from the `GetEntity` function in 400_xowa\src\gplx\xowa\xtns\scribunto\libs\Scrib_lib_wikibase.java

`GetEntity` calls `Get_wdoc_or_null` which ends up calling `Load_wdoc_or_null` in Wbase_doc_mgr (if a cache miss)

This function has the line

    Json_doc jdoc = wbase_mgr.Jdoc_parser().Parse(page.Db().Text().Text_bry());
`wbase` is an object common to all the threads
and `wbase_mgr.Jdoc_parser().Parse()` can be called in other situations not controlled by the synchronize in this thread

I see two solutions - the one I implemented was to add a synchronized block in the json `Parse`
The other is to make the json `Parse` local to each thread

**Comment by gnosygnu** [comment]
Thanks for the excellent write-up, as well as the well-thought-out options. I ended up going with "make the json `Parse` local to each thread". Specifically, have `Wbase_doc_mgr` have its own instance of a `Json_parser` rather than reuse the shared one. I think this pattern is better b/c `wbase_mgr.Jdoc_parser()` was effectively a singleton with state which is just asking for problems later.

While cleaning up `wbase_mgr.Jdoc_parser()`, I noticed that nothing else really calls it besides some one-time builder (`Xob`) commands. I'm hoping this fixes the above issue, but please feel free to reopen.

Thanks!
