### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by tsilman-marquette** [gnosygnu/xowa#836]
Win10 x64
Java 1.8.0_201

Fresh download of Xowa.
Download central generates a Javascript:void(0) error when a dump is selected. 

Error first discovered during an update on older install.

Thoughts?

**Comment by cryptikon** [comment]
Same issue here. Choosing a dump, starting and stopping download will cause a Javascript:void(0) error. However the download will still start and progress normally if you return to the download central.

**Comment by tsilman-marquette** [comment]
Yes. 
Also, I started getting a "could not find page in wiki" error after import. Main page of wiki will not open. I'm wondering if related? 
Could this be a Java versioning problem?

**Comment by tsilman-marquette** [comment]
Does not seem to be a java versioning problem. Update of Java did not fix.

**Comment by tsilman-marquette** [comment]
I tried an older iceboxed version v4.6.5.1911 with the en.wikipedia.org Wiki 
It does not display the javascript error. 
DownloadCentral displays and works as it is supposed to.

**Comment by gnosygnu** [comment]
Hey all. Sorry for the lack of response on my side. The last two weeks have been brutal for me (and the last few months have not been any better)

I uploaded a fix to handle the issue. Whenever you get a chance, try https://github.com/gnosygnu/xowa/releases/tag/v4.6.15.2101 and let me know.

Other details below.

Thanks!

---

This bug looks like it's related to the SWT upgrade back in https://github.com/gnosygnu/xowa/issues/687. Hence tsilman-marquette@'s discovery that the issue was not broken in 4.6.5.1911.

The problem looks like the SWT upgrade no longer auto-handles `javascript:` links. I've changed the code to manually fire the `javascript:` link and exit.

Also, DownloadCentral isn't supported at the moment. A bunch of untriaged bugs were reported, and I haven't been able to investigate.

If you're looking for a recent copy of English Wikipedia, you'll have to download them manually from 
 https://archive.org/details/Xowa_enwiki_2020-08

Finally, I like to credit users for finding bugs. There will be a link the XOWA change log that reads `Gui: Manually fire javascript event and exit [#836] {detected by anonymous1, anonymous2}`. Let me know if you'd like to remain anonymous or would like to be cited by nick: @tsilman-marquette  @cryptikon

**Comment by cryptikon** [comment]
Works well now. Thanks for taking care of this!

**Comment by cryptikon** [comment]
Also, I wanted to mention that even if the DownloadCentral is unsupported it needs to be at least functional or else new users will be confused and refuse to further use the program. XOWA is already more complex than alternative offline wiki solutions, the DownloadCentral is by far the easiest method of getting it working and a lot of the documentation pages still recommend using it.

As for the archive.org download. I already found that download after some searching on archive.org. However the torrent download appears to be incomplete and is missing most of the necessary files.

It also does not appear to be mentioned anywhere on xowa.org/home/wiki. Do you accept changes by volunteers on that documentation page @gnosygnu? The link should probably be added to xowa.org/home/wiki/App/Import/English_Wikipedia.html.

And as far as credit for finding bugs is concerned. I have no objection to my nick being mentioned, thank you.

**Comment by tsilman-marquette** [comment]
Dude. I am a thumb fingered engineer who just described a problem... 
Please, take the credit for fixing. I'm just glad to help in a small (really small) way. 

I like Xowa. Keep up the good work...

**Comment by GoblinLegislator** [comment]
This also fixed not being able to remove bookmarks in xowa app, thanks.
