### ISSUE TITLE
Purging old/unused wiki database files

### ISSUE THREAD

**Issue by markusmaresch** [gnosygnu/xowa#93]
For about 2 years now I have continuously been updating the xowa/wiki's I am interested.
Some format changes were done, now we have Download Central, which is really great !
But old stuff keeps building up - I believe, but am not sure.
Could you shed some light on what can go ?

My list of 'old' files, achieved by:
cd xowa/wiki;
find \* -type f -maxdepth 2 -mtime +182 | grep -v file-core.xowa | xargs ls -tla | cut -c28-999 > wiki_old.txt;

Reasoning: Files older than half a year, excluding what looks like the user preference database, sorted by age. Attached: my wiki_old.txt

Questions:
- many old files are like: *_-text-ns-_*.xowa ... can they be removed ?
- other things that can go - or are outdated ?

Thanks a lot - really cool project.
Markus

[wiki_old.txt](https://github.com/gnosygnu/xowa/files/557880/wiki_old.txt)

**Comment by gnosygnu** [comment]
> For about 2 years now I have continuously been updating the xowa/wiki's I am interested.

Cool! Thanks for keeping up with it for the past two years.

> Some format changes were done, now we have Download Central, which is really great !

Happy to hear! I'm really hoping Download Central simplifies getting wikis in general

> But old stuff keeps building up - I believe, but am not sure.
> Could you shed some light on what can go ?
> many old files are like: *-text-ns-*.xowa ... can they be removed ?

Yup, they can be removed.

First, "-text-" files are Wikitext databases. They contain the wikitext (or the "source code" for the HTML). You can read more at http://xowa.org/home/wiki/App/Databases/Overview

Right now, Download Central is only providing "-html-" databases. This is the final HTML: what you see when you visit any Wikipedia page. It doesn't have the Wikitext (the "source code")

So, unless you want the Wikitext, you can easily remove the "-text-" databases.

If you do want the Wikitext, let me know. I'm not adding them to Download Central now because:
* They are almost as large in size as the HTML databases. This makes them painful to upload.
* Most users won't find them useful
* I didn't want to clutter up Download Central with more entries.

If there is more interest in the Wikitext databases, I'll integrate them into Download Central

> other things that can go - or are outdated ?

Well, in no particular order:
* all the following wikis can be replaced with the 2016-10 version in Download Central (I think you've probably done this already)
    * de.wikiversity.org
    * de.wikibooks.org
    * de.wikiquote.org
    * de.wikivoyage.org
    * de.wikisource.org
    * de.wiktionary.org
    * de.wikipedia.org
    * www.wikidata.org
    * en.wikiversity.org
    * en.wikibooks.org
    * en.wikiquote.org
    * en.wikivoyage.org
    * en.wikisource.org
    * en.wiktionary.org
    * en.wikipedia.org
    * species.wikimedia.org
* Incubator can go. I don't think that's a useful wiki
* Commons can also go. I also don't think that's a useful wiki for offline purposes, but I'll be uploading the 2016-10 version this weekend

Also, some explanations about some of the other XOWA file "suffixes"
* **-text-**: Wikitext as described above. You can delete these if you don't care about having the "source"
* **-html-**: HTML databases as described above. You can delete these if you have later "-html-" files from a later version. For example, your 2016-04-21 de.wiktionary.org-html.xowa can be deleted if you've downloaded the corresponding "-html-" databases for 2016-10-01
* **-core**: The main database for an XOWA wiki. You can delete these if you have the later "-core" file from a later version.

> Thanks a lot - really cool project.

No problem! Glad you're finding it useful. :)

**Comment by gnosygnu** [comment]
I'm going to mark this issue closed as I think the question has been answered. Please feel free to reopen if there is anything else outstanding. Thanks.
