### ISSUE TITLE
XOWA failed to run

### ISSUE THREAD

**Issue by PhongTong** [gnosygnu/xowa#94]
Here's the error message

Sorry! XOWA failed to run!

Please check the TROUBLESHOOTING section in the readme.txt for known issues.

You can also open an issue or send an email with the data below.

Thanks!

----
OS: windows
Java: 1.8.0_111 (32 bit)
Java path: C:\Program Files\Java\jre1.8.0_111
XOWA: 3.5.1.1
XOWA path: E:\Xowa\xowa_windows.jar

Error: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
Stack: org.sqlite.core.NativeDB._open(Native Method)
org.sqlite.core.DB.open(DB.java:161)
org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
org.sqlite.JDBC.createConnection(JDBC.java:114)
org.sqlite.JDBC.connect(JDBC.java:88)
java.sql.DriverManager.getConnection(Unknown Source)
java.sql.DriverManager.getConnection(Unknown Source)
gplx.dbs.engines.Db_engine_sql_base.Conn_make_by_url(Unknown Source)
gplx.dbs.engines.sqlite.Sqlite_engine.Conn_make(Unknown Source)
gplx.dbs.engines.Db_engine_sql_base.Conn_assert(Unknown Source)
gplx.dbs.engines.Db_engine_sql_base.Stmt_by_sql(Unknown Source)
gplx.dbs.qrys.Db_stmt_cmd.Reset_stmt(Unknown Source)
gplx.dbs.qrys.Db_stmt_cmd.Ctor_stmt(Unknown Source)
gplx.dbs.qrys.Db_stmt_cmd.<init>(Unknown Source)
gplx.dbs.engines.sqlite.Sqlite_stmt.<init>(Unknown Source)
gplx.dbs.engines.sqlite.Sqlite_engine.Stmt_by_qry(Unknown Source)
gplx.dbs.engines.sqlite.Sqlite_schema_mgr.Init(Unknown Source)
gplx.dbs.engines.sqlite.Sqlite_schema_mgr.Tbl_exists(Unknown Source)
gplx.dbs.engines.sqlite.Sqlite_engine.Meta_tbl_exists(Unknown Source)
gplx.dbs.Db_conn.Meta_tbl_exists(Unknown Source)
gplx.xowa.users.data.Xou_db_file.Init_assert(Unknown Source)
gplx.xowa.users.data.Xou_db_mgr.Init_by_app(Unknown Source)
gplx.xowa.users.Xoue_user.Init_by_app(Unknown Source)
gplx.xowa.Xoae_app.Init_by_app(Unknown Source)
gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
gplx.xowa.Xoa_app_.Run(Unknown Source)
gplx.xowa.Xowa_main.main(Unknown Source)

**Comment by gnosygnu** [comment]
Hi! Thanks for the crash dump.

I tried to reproduce now, but couldn't. See more detail below.

For now, can you try a fresh install in a different folder? Specifically:
* Download the latest XOWA Windows 32-bit version from https://github.com/gnosygnu/xowa/releases/download/v3.10.4.1/xowa_app_windows_v3.10.4.1.zip
* Unzip it to E:\xowa_test (or something like that)
* Double-click the xowa.exe.

Given the above:
* If it still fails, paste the crash dump up here. I'll have to investigate the error more on my side
* If it works, you can then copy all the files in E:\xowa_test to E:\xowa. Run E:\xowa\xowa.exe again and it should work.

Hope this helps. Thanks!

----

Some notes about my attempt:
* I actually don't have 3.5.1.1 around. I must have deleted this folder on my machine.
* I tried with v3.6.3.1 and it worked. It was a 1.8 JRE on a Windows 32-bit machine
* The error itself indicates some sort of fatal error in opening the database. This could happen because:
    * The SQLite jar file hit some weird snag on your system
    * The database is corrupt at E:\xowa\user\xowa.user.anonymous.sqlite3

Both of these are low likelihood events, so I'm puzzled why either would occur

**Comment by PhongTong** [comment]
Sorry for the very late reply. I've re-installed both java se and xowa and it's working fine now :)

Thank you

**Comment by PhongTong** [comment]
Other thing, can you make Xowa auto-update itself or can updated by one-click button?

**Comment by gnosygnu** [comment]
> Sorry for the very late reply. I've re-installed both java se and xowa and it's working fine now :)

Cool. Thanks for the feedback, and no worries on the late reply. I'm going to guess that the XOWA reinstall fixed it.

> Other thing, can you make Xowa auto-update itself or can updated by one-click button?

It's been on my todo list for a while. I'll take a look at it, and comment here again before I close the ticket.

Let me know if there's anything else. Thanks!

**Comment by PhongTong** [comment]
Thank you :)

**Comment by gnosygnu** [comment]
I created a ticket for an auto-update feature at #110. I'll post further progress there.

In the meantime, I'm going to close out this ticket. Let me know if there's anything else. Thanks.
