### ISSUE TITLE
{{NUMBEROFPAGES}} and {{NUMBEROFARTICLES}} swapped; Multi-language variants broken; Offline to online submission; Category needs "latest" for Import/Offline (Three issues on XOWA)

### ISSUE THREAD

**Issue by AlexanderMisel** [gnosygnu/xowa#97]
I am using xowa_app_windows_64_v3.10.4.6.

First one is about magic words `{{NUMBEROFPAGES}}` and `{{NUMBEROFARTICLES}}`, the number showed by XOWA are reversed. For Chinese Wikipedia, it should be 2,856,661 and 908,113, but it showed 908,113 and 2,856,661.

Second one is that support for content language variant conversion for Chinese should be improved. For example, we use in-page conversion like `-{zh-hans:computer; zh-hant:ELECTRONICBRAIN;}-`, see https://www.mediawiki.org/wiki/Writing_systems/Syntax for the **bidirectional** syntax. But XOWA simply shows `zh-hans:computer; zh-hant:ELECTRONICBRAIN;` without parsing the conversion.

Third one is that I hope my edits on XOWA could be published online by just clicking a button or so to publish the my version on Wikipedia, maybe after configuring the username and password. By the way I love using XOWA as an offline sandbox for Wikipedia editing. 

Moreover, on `home/wiki/Dashboard/Import/Offline#Without internet connection`, it told me to download `wiki-date-categorylinks.sql.gz` and `wiki-date-page_props.sql.gz`, but actually I discovered that it requires me to rename the `date` to `latest` when using these files, but the help page didn't mention that.

Thanks.

**Comment by gnosygnu** [comment]
Hi! Thanks for the error report and the great detail! 

I changed the title to give it some more info. I know it looks cluttered but I'm hoping all those words will make it useful.

I comment more below, but let me know if I missed anything.

> First one is about magic words {{NUMBEROFPAGES}} and {{NUMBEROFARTICLES}}, the number showed by XOWA are reversed. For Chinese Wikipedia, it should be 2,856,661 and 908,113, but it showed 908,113 and 2,856,661.

Oops. I broke this sometime in the last few months. The parser function <code>{{NUMBEROFPAGES}}</code> should read from <code>site_stats.ss_total_pages</code> while <code>{{NUMBEROFARTICLES}}</code> should read from <code>site_stats.ss_good_articles</code>. These were reversed by mistake.

This will be fixed in the next release.

> Second one is that support for content language variant conversion for Chinese should be improved. For example, we use in-page conversion like -{zh-hans:computer; zh-hant:ELECTRONICBRAIN;}-, see https://www.mediawiki.org/wiki/Writing_systems/Syntax for the bidirectional syntax. But XOWA simply shows zh-hans:computer; zh-hant:ELECTRONICBRAIN; without parsing the conversion.

XOWA actually does implement the bidi rules in https://www.mediawiki.org/wiki/Writing_systems/Syntax. Unfortunately, I broke this too recently.

This will also be fixed in the next release.

> Third one is that I hope my edits on XOWA could be published online by just clicking a button or so to publish the my version on Wikipedia, maybe after configuring the username and password. By the way I love using XOWA as an offline sandbox for Wikipedia editing.

Honestly, I'm hesitant to go this way. The main issue is that it requires a good deal of work to make sure that the offline copy and all its dependencies are up-to-date. Otherwise, the submitted edit may be posting out-of-date data. 

For example, say you're working on 2016-10-01 English Wikipedia. It's 2016-10-15 and you want to submit an edit for http://en.wikipedia.org/wiki/Earth
* First, XOWA would have to get the latest copy of Earth, because the online Earth article would probably have changed between 2016-10-01 and 2016-10-15
* Then, XOWA would have to get all Templates and Modules that are used by Earth
    * Note that Templates and Modules are deeply nested in their calls so a lot of pages will need to be checked / updated. As an example of what's involved, scroll down to the Template / Module list in https://en.wikipedia.org/w/index.php?title=Earth&action=edit
    * Also, note that once a Template is updated, other pages calling that Template can be affected. This can cause a pretty large loop where pages using that Template should also be updated (or risk being broken). For example:
       * Template:Solar_System requires a new argument as of 2016-10-10
       * On the online site, Mercury, Venus, Mars, etc. were all edited on 2016-10-10 to add the new argument
       * The offline versions of Mercury, Venus, etc. still use the old style and would be broken after bringing down the latest Template:Solar_System.
* In addition, XOWA would probably also have to get relevant Wikidata entries. This is actually complicated as Wikidata can be called from Module pages, and there's no easy way to identify dependencies (i.e.: Earth depends on Q1234 because a line of Lua code in Module:Something calls it.)
* Finally, XOWA should probably bring down the latest copies of the images (or else caption updates may be wrong)

Of course, XOWA could ignore all of the above, and just allow a blind submission of the offline wikitext to the online page. But I think even a good Wikipedian will find it hard to make an accurate edit given all the above.

Hopefully this makes sense.

> Moreover, on home/wiki/Dashboard/Import/Offline#Without internet connection, it told me to download wiki-date-categorylinks.sql.gz and wiki-date-page_props.sql.gz, but actually I discovered that it requires me to rename the date to latest when using these files, but the help page didn't mention that.

Good catch. I'll see if I can remove the hard-coded requirement on latest. If I can't, at the very least, I'll also update the doc for the next release.

Finally, I like to credit users for reporting bugs. There'll be a line in the Change log with something like "ParserFunctions: Switch {{NUMBEROFPAGES}} and {{NUMBEROFARTICLES}} {reported by anonymous}". There'll be two other entries as well. Let me know if you would like to be cited by name / nickname or would rather remain anonymous.

Thanks!

**Comment by AlexanderMisel** [comment]
Thanks for your reply. I downloaded the patched v3.10.4.7, but it seems the version is built for 32-bit JVM. 

> Error: Cannot load 32-bit SWT libraries on 64-bit JVM
> Stack: org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
> org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
> org.eclipse.swt.internal.C.<clinit>(Unknown Source)
> org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
> gplx.gfui.kits.core.Swt_kit.Kit_init(Unknown Source)
> gplx.xowa.guis.Xoa_gui_mgr.Kit_(Unknown Source)
> gplx.xowa.guis.Xoa_gui_mgr.Run(Unknown Source)
> gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
> gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
> gplx.xowa.Xoa_app_.Run(Unknown Source)
> gplx.xowa.Xowa_main.main(Unknown Source)

Would you please build a 64bit version?

**Comment by gnosygnu** [comment]
> Thanks for your reply. I downloaded the patched v3.10.4.7, but it seems the version is built for 32-bit JVM. 

Oops! Sorry about that. I uploaded the 64-bit just now: https://drive.google.com/open?id=0B9cb52zjL2rIbTJlbUxBRHJXVHc

**Comment by gnosygnu** [comment]
I just wanted to point out that these issues were resolved in Sunday evening's build: https://github.com/gnosygnu/xowa/releases/tag/v3.11.2.1

Specifically:
* <code>{{NUMBEROFPAGES}}</code> and <code>{{NUMBEROFARTICLES}}</code> now report the correct numbers
* Variants are now evaluated: <code>-{zh-hans:computer; zh-hant:ELECTRONICBRAIN;}-</code>
* Import.Offline changed to use any dump file, not just "latest"

I'm going to hold off on the Offline to Online submission item. I created an issue here to track future discussion: https://github.com/gnosygnu/xowa/issues/103 . Please feel free to comment there.

Otherwise, I'm marking this item resolved, and will probably close out in a few days. Thanks.

**Comment by gnosygnu** [comment]
As per above, this issue was resolved in v3.11.2.1. I'm going to mark this ticket closed. Thanks.
